return {
  ["T_IngDye_WhiteLead_01"] = {
    "Poison",
    { "DamageAttribute" , "Intelligence" },
    { "FortifySkill" , "Alchemy" },
    "ResistPoison",
  },
  ["TR_m1_Q59_PR_disease_meat"] = {
    "DrainMagicka",
    "Paralyze",
    "CurePoison",
    "ResistPoison",
  },
  ["T_IngFlor_RockburstClaw_01"] = {
    "Burden",
    { "FortifyAttribute" , "Endurance" },
    { "RestoreAttribute" , "Strength" },
    "ResistShock",
  },
  ["T_IngCrea_SkyrenderVenom_01"] = {
    "Poison",
    "Paralyze",
    "ResistPoison",
    "CurePoison",
  },
  ["T_IngFlor_FoxgloveNectar_01"] = {
    "ResistPoison",
    "ResistParalysis",
    { "RestoreAttribute" , "Luck" },
    "ResistCommonDisease",
  },
  ["T_IngMine_PeridotDae_01"] = {
    "FortifyHealth",
    "RestoreFatigue",
    "DrainMagicka",
    { "FortifyAttribute" , "Intelligence" },
  },
  ["T_IngFlor_CinnabarPolypore_02"] = {
    { "RestoreAttribute" , "Endurance" },
    { "FortifyAttribute" , "Endurance" },
    { "DamageAttribute" , "Personality" },
    "Reflect",
  },
  ["T_IngMine_TopazDae_01"] = {
    { "DrainAttribute" , "Strength" },
    { "FortifyAttribute" , "Intelligence" },
    "RestoreHealth",
    "FireShield",
  },
  ["T_IngFlor_YuinRoot_01"] = {
    "WeaknessToMagicka",
    "FortifyFatigue",
    "CureCommonDisease",
    "Burden",
  },
  ["T_IngFlor_PyrousUracia"] = {
    { "DrainAttribute" , "Willpower" },
    "Feather",
    { "DrainAttribute" , "Agility" },
    "Blind",
  },
  ["T_IngCrea_Ivory"] = {
    "DrainFatigue",
    "ResistCommonDisease",
    { "FortifyAttribute" , "Strength" },
    "Telekinesis",
  },
  ["T_IngFlor_BogBeacon_01"] = {
    "RestoreMagicka",
    "Shield",
    { "DamageAttribute" , "Personality" },
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngFlor_Nirnroot_01"] = {
    "RestoreMagicka",
    { "DrainAttribute" , "Speed" },
    "DetectAnimal",
    "DrainFatigue",
  },
  ["T_IngFood_WasabiRoot_01"] = {
    "WeaknessToFrost",
    { "RestoreAttribute" , "Willpower" },
    { "FortifyAttribute" , "Endurance" },
    "FireDamage",
  },
  ["T_IngFood_Vinegar_01"] = {
    "ResistFire",
    { "DrainAttribute" , "Personality" },
    { "RestoreAttribute" , "Personality" },
    "CureCommonDisease",
  },
  ["T_IngMine_AmberDae_01"] = {
    "Paralyze",
    "LightningShield",
    "WaterWalking",
    "FireShield",
  },
  ["T_IngFood_CustTartRedguard_01"] = {
    "RestoreHealth",
  },
  ["T_IngMine_AquamarineDae_01"] = {
    "DrainHealth",
    "CurePoison",
    "WaterBreathing",
    "WeaknessToFrost",
  },
  ["T_IngMine_Onyx_01"] = {
    { "DrainAttribute" , "Personality" },
    "LightningShield",
    "WeaknessToFire",
    "ResistShock",
  },
  ["T_IngCrea_Muskratfur_01"] = {
    { "DrainAttribute" , "Intelligence" },
    "FortifyHealth",
    "ResistShock",
  },
  ["T_IngFlor_Moosebite_01"] = {
    { "DamageAttribute" , "Willpower" },
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Personality" },
    "Telekinesis",
  },
  ["T_IngFlor_PorousExidia_01"] = {
    { "DrainAttribute" , "Personality" },
    "ResistCommonDisease",
    "DetectAnimal",
    { "FortifyAttribute" , "Luck" },
  },
  ["TR_m3_q_14_fish"] = {
    "DamageFatigue",
  },
  ["T_IngFlor_CarlineTh_01"] = {
    { "DrainAttribute" , "Strength" },
    "DetectAnimal",
    "DamageFatigue",
    "ResistMagicka",
  },
  ["T_IngFlor_LadysMantle_01"] = {
    "RestoreHealth",
    { "DamageAttribute" , "Endurance" },
    "NightEye",
    "Feather",
  },
  ["T_IngMine_FireOpal_01"] = {
    "WeaknessToFire",
    "FireDamage",
    "FireShield",
    "ResistFire",
  },
  ["T_IngFlor_PadomaicSage_01"] = {
    "CurePoison",
    { "FortifyAttribute" , "Endurance" },
    "RestoreHealth",
    "ResistCommonDisease",
  },
  ["T_IngFlor_Monkshood_01"] = {
    { "RestoreAttribute" , "Strength" },
    { "DamageAttribute" , "Intelligence" },
    { "FortifyAttribute" , "Endurance" },
    "Burden",
  },
  ["T_IngFood_BridethornBerry_01"] = {
    "ResistFrost",
    "FortifyFatigue",
    "Reflect",
    "Poison",
  },
  ["T_IngMine_PearlKardesh_01"] = {
    "Silence",
    "WaterBreathing",
    { "DamageAttribute" , "Luck" },
    { "FortifyAttribute" , "Intelligence" },
  },
  ["T_IngMine_Realgar_01"] = {
    "Poison",
    { "FortifySkill" , "Alchemy" },
    "ResistMagicka",
  },
  ["T_IngFood_AppleSkyrim_01"] = {
    "RestoreFatigue",
    { "DamageAttribute" , "Willpower" },
    { "FortifyAttribute" , "Speed" },
  },
  ["T_IngFood_CheeseRedguard_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Willpower" },
    "ResistPoison",
  },
  ["T_IngFlor_MountainDamask"] = {
    "Burden",
    { "FortifyAttribute" , "Agility" },
    "FortifyHealth",
  },
  ["T_IngCrea_Trollfat_01"] = {
    "WeaknessToFire",
    { "FortifyAttribute" , "Personality" },
    { "DamageAttribute" , "Willpower" },
    "DamageHealth",
  },
  ["TR_m1_ingred_ceph_shell_uni"] = {
    "DrainFatigue",
    "DrainHealth",
  },
  ["T_IngFlor_LichenYellow_01"] = {
    { "FortifyAttribute" , "Agility" },
    "Poison",
    "ResistFire",
    "DrainHealth",
  },
  ["T_IngFlor_TinderPolypore_01"] = {
    { "RestoreAttribute" , "Willpower" },
    "ResistCommonDisease",
    "Invisibility",
    "DamageMagicka",
  },
  ["T_IngFlor_BlisterSpore_01"] = {
    "FortifyHealth",
    "WeaknessToPoison",
    "Poison",
    "Blind",
  },
  ["T_IngFlor_Mustard_01"] = {
    "FortifyFatigue",
    "Blind",
    "ResistFrost",
    "WeaknessToPoison",
  },
  ["T_IngFlor_Maidenhair_01"] = {
    "SlowFall",
    { "DrainAttribute" , "Speed" },
    { "FortifyAttribute" , "Luck" },
    { "DrainAttribute" , "Personality" },
  },
  ["T_IngFood_Sfiha_01"] = {
    "RestoreFatigue",
    "FortifyAttack",
    "DamageMagicka",
  },
  ["T_IngMine_Amber_01"] = {
    "Paralyze",
    "LightningShield",
    "WaterWalking",
    "FireShield",
  },
  ["T_IngCrea_GremlinEarWax_01"] = {
    "Blind",
    "Paralyze",
    "ResistShock",
  },
  ["T_IngFlor_Asteria_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Speed" },
    { "RestoreAttribute" , "Intelligence" },
    "Light",
  },
  ["T_IngFood_MeatPork_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Speed" },
    "FortifyFatigue",
  },
  ["T_IngFlor_Blknet_01"] = {
    "Blind",
    { "DrainAttribute" , "Intelligence" },
    "DrainHealth",
    "ResistCommonDisease",
  },
  ["T_IngFlor_ShutagJelly_01"] = {
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Agility" },
    "WeaknessToFrost",
    { "RestoreSkill" , "Athletics" },
  },
  ["T_IngFood_MeatGoat_01"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Agility" },
  },
  ["T_IngFlor_Glowshroom"] = {
    "Light",
    { "DamageAttribute" , "Agility" },
    { "RestoreAttribute" , "Endurance" },
    "NightEye",
  },
  ["T_IngFood_TeaAltmer_01"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Intelligence" },
    "FortifyFatigue",
    { "DamageAttribute" , "Agility" },
  },
  ["T_IngMine_Chalk_01"] = {
    { "DrainAttribute" , "Speed" },
    "Mark",
  },
  ["T_IngMine_Jet_01"] = {
    "DamageFatigue",
    { "RestoreAttribute" , "Personality" },
    "WeaknessToFire",
    "Dispel",
  },
  ["T_IngMine_Flashgrit_01"] = {
    "FireDamage",
    "Reflect",
    "Jump",
    "NightEye",
  },
  ["TR_i3-685_OutlawsBlood"] = {
    "WaterWalking",
    "Sanctuary",
  },
  ["T_IngFlor_VicarHerb_01"] = {
    "DamageFatigue",
    "RestoreHealth",
    "CureCommonDisease",
    "Burden",
  },
  ["T_IngFood_Flour_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
  },
  ["T_IngMine_PearlBlueDae_01"] = {
    { "DamageAttribute" , "Intelligence" },
    "WaterBreathing",
    "RestoreMagicka",
    "FortifyMaximumMagicka",
  },
  ["T_IngMine_DiamondRed_01"] = {
    { "DrainAttribute" , "Endurance" },
    "Invisibility",
    "Reflect",
    "ResistFire",
  },
  ["T_IngFlor_Sugarcane_01"] = {
    { "FortifyAttribute" , "Speed" },
    { "DrainAttribute" , "Endurance" },
    { "DrainAttribute" , "Luck" },
  },
  ["T_IngFlor_CanisRoot_01"] = {
    "DrainFatigue",
    { "DrainAttribute" , "Speed" },
    "FortifyHealth",
    "Paralyze",
  },
  ["T_IngCrea_FlyMusk_01"] = {
    { "DamageAttribute" , "Personality" },
    "DamageHealth",
    { "FortifySkill" , "Speechcraft" },
  },
  ["T_IngFood_CloudyCorn_01"] = {
    "RestoreFatigue",
    "Feather",
    { "DrainAttribute" , "Luck" },
    "FortifyHealth",
  },
  ["T_IngFlor_Woadfl_01"] = {
    "DamageFatigue",
    "DrainHealth",
    { "FortifyAttribute" , "Strength" },
    "ResistMagicka",
  },
  ["T_IngFlor_KingThistle_01"] = {
    "DrainFatigue",
    "FortifyHealth",
    "FortifyFatigue",
    "DamageMagicka",
  },
  ["T_IngFood_Olives_01"] = {
    "Sanctuary",
    { "DrainAttribute" , "Strength" },
    { "FortifyAttribute" , "Agility" },
    "WeaknessToFire",
  },
  ["T_IngFood_CheeseBreton_02"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Endurance" },
    { "FortifyAttribute" , "Willpower" },
  },
  ["T_IngFlor_SucculentPulp_01"] = {
    "RestoreFatigue",
    { "RestoreAttribute" , "Endurance" },
  },
  ["T_IngFlor_SaltstrapPollen_01"] = {
    "Paralyze",
    "LightningShield",
    "DisintegrateArmor",
    "ShockDamage",
  },
  ["TR_m4_q_AG_gift"] = {
    "WeaknessToFrost",
    "FrostDamage",
    "FrostShield",
    "ResistFrost",
  },
  ["T_IngMine_OreOrichalcum_01"] = {
    "DamageMagicka",
    "DetectEnchantment",
    "Burden",
    "StuntedMagicka",
  },
  ["T_IngFood_EggMolecrab_01"] = {
    "RestoreHealth",
  },
  ["T_IngFood_MeatHorse_01"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Speed" },
  },
  ["TR_m7_q_Ns_IC8_gem2"] = {
    "DrainHealth",
    "Feather",
    { "RestoreAttribute" , "Intelligence" },
    { "DrainAttribute" , "Agility" },
  },
  ["T_IngCrea_IronToadHide"] = {
    "Burden",
    "SwiftSwim",
    "WeaknessToFrost",
    "FortifyHealth",
  },
  ["T_IngCrea_BeetleResin_01"] = {
    "DrainFatigue",
    "RestoreHealth",
    { "DrainAttribute" , "Willpower" },
    { "FortifyAttribute" , "Endurance" },
  },
  ["T_IngFood_PassionFruit_01"] = {
    "RestoreFatigue",
    "Feather",
    { "DrainAttribute" , "Luck" },
  },
  ["T_IngFood_MeatGuar_01"] = {
    "RestoreFatigue",
    "ResistFrost",
  },
  ["T_IngFlor_BjoulsaeRose_01"] = {
    { "FortifyAttribute" , "Personality" },
    { "DrainAttribute" , "Agility" },
    "Sanctuary",
  },
  ["T_IngMine_PearlBlack_01"] = {
    "Silence",
    "WaterBreathing",
    { "DamageAttribute" , "Endurance" },
    { "FortifyAttribute" , "Personality" },
  },
  ["T_IngMine_EmeraldDeTomb_01"] = {
    "FortifyMagicka",
    "RestoreHealth",
    { "DrainAttribute" , "Agility" },
    { "DrainAttribute" , "Endurance" },
  },
  ["T_IngFood_BreadKeptu_01"] = {
    "RestoreHealth",
  },
  ["TR_m7_Dradivas_Stone"] = {
    "FortifyMagicka",
    "RestoreHealth",
    { "DrainAttribute" , "Agility" },
    { "DrainAttribute" , "Endurance" },
  },
  ["T_IngFood_Gorapple_01"] = {
    "RestoreFatigue",
    "RestoreHealth",
    "DrainMagicka",
    { "FortifyAttribute" , "Willpower" },
  },
  ["T_IngCrea _GremlinEarWax_01"] = {
    "Blind",
    "Paralyze",
    "ResistShock",
  },
  ["T_IngFood_FishSpr_01"] = {
    "RestoreFatigue",
    "SwiftSwim",
    { "DamageAttribute" , "Luck" },
    "DrainMagicka",
  },
  ["T_IngMine_OreSilver_01"] = {
    { "DrainAttribute" , "Personality" },
    "Burden",
    "ResistCommonDisease",
    "LightningShield",
  },
  ["TR_i3-280_ingred_cursed_diamond"] = {
    { "DrainAttribute" , "Agility" },
    "Invisibility",
    "Reflect",
    "DetectKey",
  },
  ["T_IngCrea_ButterflyWingCyr_02"] = {
    { "RestoreAttribute" , "Personality" },
    "Feather",
    { "DamageAttribute" , "Endurance" },
    "WaterBreathing",
  },
  ["T_IngMine_SpinelDae_01"] = {
    "WeaknessToMagicka",
    "CureParalyzation",
    "Dispel",
    "DamageHealth",
  },
  ["T_IngMine_Moonstone_01"] = {
    "DamageHealth",
    "Reflect",
    "Light",
    { "DrainAttribute" , "Willpower" },
  },
  ["T_IngFlor_NoddingStreakwort"] = {
    "Blind",
    "LightningShield",
    { "FortifySkill" , "Acrobatics" },
    "DrainFatigue",
  },
  ["T_IngCrea_MothWingMw_01"] = {
    "Paralyze",
    { "DrainAttribute" , "Agility" },
    "ResistBlightDisease",
    "Levitate",
  },
  ["T_IngCrea_PrismaticDust_01"] = {
    "Light",
    "LightningShield",
    "Blind",
    "RestoreMagicka",
  },
  ["T_IngFood_Garlic_01"] = {
    "RestoreFatigue",
    "ResistCommonDisease",
    { "DrainAttribute" , "Personality" },
    "RestoreHealth",
  },
  ["T_IngCrea_Starfish_01"] = {
    "WaterBreathing",
    "WeaknessToCommonDisease",
    "SwiftSwim",
    "CureCommonDisease",
  },
  ["TR_m3_TT_JalorPowder"] = {
    "DamageHealth",
    "DamageFatigue",
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngMine_Charcoal_01"] = {
    "Sound",
    "DrainHealth",
    "CureCommonDisease",
    "ResistFire",
  },
  ["T_IngCrea_CanahFeather"] = {
    "Levitate",
    { "FortifyAttribute" , "Personality" },
    { "DrainAttribute" , "Intelligence" },
    { "RestoreAttribute" , "Endurance" },
  },
  ["T_IngFlor_BlackrosePetalDae_01"] = {
    { "FortifyAttribute" , "Personality" },
    "DrainFatigue",
    "Poison",
    "Invisibility",
  },
  ["Sky_qRe_KWMG5_PadPersarine"] = {
    { "RestoreAttribute" , "Personality" },
    { "FortifyAttribute" , "Luck" },
    "ResistMagicka",
  },
  ["T_IngCrea_DWyrmGland"] = {
    "Poison",
    "WeaknessToMagicka",
    "DetectAnimal",
    "CurePoison",
  },
  ["T_IngMine_OreOrichalcum_02"] = {
    "DamageMagicka",
    "Burden",
  },
  ["T_IngFlor_NightshadeDae_01"] = {
    "DamageHealth",
    "Burden",
    { "DamageAttribute" , "Luck" },
    "FortifyMagicka",
  },
  ["T_IngCrea_DonkeyHide_01"] = {
    { "DrainAttribute" , "Personality" },
    { "FortifyAttribute" , "Endurance" },
    { "RestoreAttribute" , "Strength" },
  },
  ["T_IngCrea_BeetleShell_03"] = {
    { "FortifyAttribute" , "Endurance" },
    "DetectAnimal",
  },
  ["T_IngCrea_MothWingMw_03"] = {
    "DrainHealth",
    "ResistParalysis",
    "Sound",
    "ResistNormalWeapons",
  },
  ["T_IngFlor_Redpoppy_01"] = {
    { "DrainAttribute" , "Strength" },
    "ResistFire",
    { "RestoreAttribute" , "Endurance" },
    "RestoreFatigue",
  },
  ["T_IngFood_FishStrid_01"] = {
    "RestoreFatigue",
    "Feather",
    "WeaknessToShock",
    "WaterWalking",
  },
  ["T_IngFlor_Alkanet_01"] = {
    { "RestoreAttribute" , "Intelligence" },
    "ResistPoison",
    "Light",
    "DamageFatigue",
  },
  ["T_IngMine_TopazBlue_01"] = {
    { "DrainAttribute" , "Endurance" },
    { "FortifyAttribute" , "Willpower" },
    "RestoreMagicka",
    "FrostShield",
  },
  ["T_IngCrea_HumanHeart"] = {
    "DamageHealth",
    "DamageMagicka",
    { "DamageAttribute" , "Intelligence" },
    { "DamageAttribute" , "Willpower" },
  },
  ["T_IngFlor_MorningGlory_01"] = {
    { "RestoreAttribute" , "Agility" },
    { "DamageAttribute" , "Speed" },
    { "FortifyAttribute" , "Willpower" },
    "Blind",
  },
  ["T_IngCrea_HorkerPupPelt_01"] = {
    "ResistFrost",
    "SwiftSwim",
    "DrainHealth",
  },
  ["T_IngFlor_Bearclaw_01"] = {
    { "DrainAttribute" , "Willpower" },
    "FortifyHealth",
    { "RestoreAttribute" , "Strength" },
    "FortifyAttack",
  },
  ["T_IngCrea_RocFeather"] = {
    { "FortifyAttribute" , "Agility" },
    "StuntedMagicka",
    "ResistFire",
    "Shield",
  },
  ["T_IngFood_LotteFruit_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Willpower" },
    { "RestoreSkill" , "Speechcraft" },
    "DrainFatigue",
  },
  ["T_IngFlor_FennelSeed_01"] = {
    "DamageMagicka",
    { "DamageAttribute" , "Intelligence" },
    "Telekinesis",
    "Paralyze",
  },
  ["T_IngMine_AmethystDae_01"] = {
    "ResistPoison",
    "DrainFatigue",
    "CureCommonDisease",
    { "RestoreAttribute" , "Willpower" },
  },
  ["T_IngFlor_SaltstrapLeaf_01"] = {
    "DrainFatigue",
    "WeaknessToShock",
  },
  ["TR_m2_q_29_4_silk"] = {
    "Burden",
    "NightEye",
    "Chameleon",
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngFlor_Ginseng_01"] = {
    { "DamageAttribute" , "Luck" },
    "CurePoison",
    "Burden",
    "FortifyMagicka",
  },
  ["T_IngFlor_SujPod_01"] = {
    "RestoreFatigue",
    "Sound",
    { "DrainAttribute" , "Personality" },
    "CureCommonDisease",
  },
  ["T_IngFlor_Tacca_01"] = {
    "DrainMagicka",
    { "FortifyAttribute" , "Strength" },
    "FortifyAttack",
    "WeaknessToPoison",
  },
  ["T_IngFood_Sfiha_02"] = {
    "RestoreFatigue",
    "FortifyAttack",
    "DamageMagicka",
  },
  ["T_IngCrea_Trichobezoar_01"] = {
    "CurePoison",
    "ResistPoison",
    { "FortifySkill" , "Alchemy" },
    { "DrainAttribute" , "Personality" },
  },
  ["T_IngFlor_Draketail_01"] = {
    { "DrainAttribute" , "Endurance" },
    { "FortifyAttribute" , "Luck" },
    "FireShield",
    "Paralyze",
  },
  ["T_IngFlor_Bleakbell_01"] = {
    "FortifyFatigue",
    "FrostDamage",
    "DetectEnchantment",
    { "RestoreAttribute" , "Strength" },
  },
  ["T_IngSpice_Saffron_01"] = {
    { "DrainAttribute" , "Endurance" },
    "NightEye",
    { "FortifyAttribute" , "Personality" },
    { "RestoreAttribute" , "Personality" },
  },
  ["T_IngCrea_CephalopodShell_01"] = {
    "Poison",
    "SwiftSwim",
    "WaterBreathing",
    "Shield",
  },
  ["T_IngMine_Jade_01"] = {
    "FortifyHealth",
    "RestoreHealth",
    { "FortifySkill" , "Alchemy" },
    "Poison",
  },
  ["T_IngFood_TartRedguard_01"] = {
    "RestoreMagicka",
    "FortifyHealth",
    "DrainFatigue",
  },
  ["T_IngFlor_SocrataNectar_01"] = {
    "CureCommonDisease",
    "DrainFatigue",
    "FireShield",
    "Burden",
  },
  ["T_IngMine_JetDae_01"] = {
    "DamageFatigue",
    { "RestoreAttribute" , "Personality" },
    "WeaknessToFire",
    "Dispel",
  },
  ["T_IngFlor_Comatus_01"] = {
    { "FortifyAttribute" , "Endurance" },
    { "DamageAttribute" , "Strength" },
    "DrainHealth",
    { "RestoreAttribute" , "Intelligence" },
  },
  ["T_IngFlor_DomicaRedwort_01"] = {
    { "FortifyAttribute" , "Personality" },
    "CurePoison",
    "DamageHealth",
    "Invisibility",
  },
  ["T_IngFlor_FlaxFlower_03"] = {
    "FortifyFatigue",
    { "FortifySkill" , "LightArmor" },
    "WeaknessToFire",
    "Dispel",
  },
  ["T_IngCrea_ClamMeat"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Endurance" },
    "WaterWalking",
  },
  ["T_IngFlor_BlisteringFoment_01"] = {
    { "DrainAttribute" , "Intelligence" },
    "Levitate",
    "DrainHealth",
    "Paralyze",
  },
  ["T_IngFlor_VileMorchella_01"] = {
    "DamageHealth",
    "Invisibility",
    "Poison",
    { "FortifyAttribute" , "Agility" },
  },
  ["T_IngCrea_DaedricBatEye_01"] = {
    "NightEye",
    "DetectAnimal",
    "Levitate",
  },
  ["T_IngMine_OreIron_01"] = {
    { "DrainAttribute" , "Speed" },
    "Burden",
    { "FortifyAttribute" , "Endurance" },
    "FortifyFatigue",
  },
  ["T_IngFood_Onion_01"] = {
    "RestoreFatigue",
    "ResistPoison",
    { "DamageAttribute" , "Personality" },
    "Paralyze",
  },
  ["TR_m7_AHPicnicCabbage"] = {
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Intelligence" },
  },
  ["T_IngCrea_RakiTeeth_01"] = {
    "DrainHealth",
    "WeaknessToShock",
    "NightEye",
    "Jump",
  },
  ["T_IngFlor_MarshStalk_01"] = {
    { "DrainAttribute" , "Strength" },
    "Poison",
    "DetectAnimal",
    "ResistMagicka",
  },
  ["T_IngFlor_WtLillyYellow_01"] = {
    "WaterWalking",
    { "DrainAttribute" , "Agility" },
    "Paralyze",
    "Levitate",
  },
  ["T_IngFlor_RustblossomSeed_01"] = {
    "RestoreFatigue",
    "Burden",
    "FireShield",
  },
  ["T_IngMine_OreGold_01"] = {
    { "DrainAttribute" , "Willpower" },
    "Burden",
    "ResistParalysis",
    { "FortifyAttribute" , "Personality" },
  },
  ["TR_m4_q_VM_BlueCarbuncle_UNI"] = {
    "DamageHealth",
    "Shield",
    "ResistMagicka",
    "DamageFatigue",
  },
  ["T_IngCrea_HirvHide_01"] = {
    "Burden",
    "Sound",
    { "DrainAttribute" , "Agility" },
    { "FortifyAttribute" , "Endurance" },
  },
  ["T_IngFood_BreadKeptu_03"] = {
    "RestoreHealth",
  },
  ["T_IngMine_Turquoise_01"] = {
    { "DrainAttribute" , "Willpower" },
    "WaterWalking",
    { "DamageAttribute" , "Endurance" },
    "Sanctuary",
  },
  ["T_IngFood_FishChrysophant_01"] = {
    "RestoreFatigue",
    "DrainMagicka",
    { "DamageAttribute" , "Endurance" },
    { "RestoreAttribute" , "Strength" },
  },
  ["T_IngCrea_MothWingCyr_03"] = {
    "CureParalyzation",
    "SlowFall",
    "WeaknessToFire",
    { "FortifyAttribute" , "Willpower" },
  },
  ["T_IngCrea_DurzogHide_01"] = {
    "DrainFatigue",
    "SwiftSwim",
    "ResistParalysis",
    "Blind",
  },
  ["T_IngFlor_ThorntailFlower_01"] = {
    { "DrainAttribute" , "Strength" },
    { "FortifyAttribute" , "Agility" },
    { "DrainAttribute" , "Speed" },
    "CurePoison",
  },
  ["T_IngFlor_LoversRaflesiaPistil"] = {
    { "DamageAttribute" , "Willpower" },
    { "FortifyAttribute" , "Personality" },
    "WeaknessToMagicka",
  },
  ["T_IngCrea_MoonMothWing_01"] = {
    "Feather",
    "DivineIntervention",
    { "FortifyAttribute" , "Intelligence" },
    "Reflect",
  },
  ["Sky_iRe_Barrow99_Heart"] = {
    "ResistFrost",
    "LightningShield",
    "DrainFatigue",
    "RestoreHealth",
  },
  ["T_IngMine_FoolsGold_01"] = {
    { "FortifyAttribute" , "Luck" },
    "Burden",
    "Blind",
    { "DamageAttribute" , "Intelligence" },
  },
  ["T_IngMine_OreMercury_01"] = {
    "DamageHealth",
    "Reflect",
    "Blind",
    "Poison",
  },
  ["T_IngCrea_KwamaChitin_01"] = {
    "WeaknessToPoison",
    "Poison",
  },
  ["TR_i4-507_ingred_hla_pearl"] = {
    { "DrainAttribute" , "Agility" },
    "Dispel",
    "WaterBreathing",
    "ResistCommonDisease",
  },
  ["TR_m3_OE_q_HorseMeat"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Speed" },
  },
  ["T_IngCrea_BeetleShell_02"] = {
    { "FortifyAttribute" , "Endurance" },
    "Reflect",
  },
  ["T_IngFlor_AlchemistsGlobe_01"] = {
    { "FortifySkill" , "Alchemy" },
    "Poison",
    "ResistParalysis",
    "FireShield",
  },
  ["T_IngMine_KhajiitEyeDae_01"] = {
    "WeaknessToCommonDisease",
    "NightEye",
    { "DrainAttribute" , "Personality" },
    { "FortifyAttribute" , "Speed" },
  },
  ["TR_m7_Kalk_Evenfall_Sapphire"] = {
    "DamageHealth",
    "Shield",
    "ResistMagicka",
    "DamageFatigue",
  },
  ["T_IngFood_PoppadGourd_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Agility" },
    { "DamageAttribute" , "Personality" },
  },
  ["T_IngFlor_WormWh02"] = {
    { "DamageAttribute" , "Endurance" },
    "DrainFatigue",
    "Feather",
    "ResistMagicka",
  },
  ["T_IngMine_Agate_01"] = {
    "Reflect",
    "Levitate",
    "Silence",
  },
  ["TR_m2_q_22_Dust"] = {
  },
  ["T_IngFood_BreadFlat_01"] = {
    "RestoreHealth",
  },
  ["T_IngFlor_FlaxFlower_01"] = {
    "FortifyFatigue",
    { "FortifySkill" , "LightArmor" },
    "WeaknessToFire",
    "FrostShield",
  },
  ["T_IngFood_EggSeagull_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Endurance" },
    { "DrainAttribute" , "Luck" },
    "Feather",
  },
  ["T_IngFlor_IronwoodNut_01"] = {
    "Paralyze",
    "FortifyHealth",
    { "FortifyAttribute" , "Strength" },
    "DetectAnimal",
  },
  ["T_IngFlor_Cabbage_01"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Intelligence" },
    "FortifyHealth",
  },
  ["T_IngFlor_Hemlock_01"] = {
    "Poison",
    "Paralyze",
    "FireDamage",
    "ResistFrost",
  },
  ["TR_m1_Q_Ingred_Topaz"] = {
    "FireDamage",
    "ResistMagicka",
    "RestoreHealth",
    "SummonScamp",
  },
  ["T_IngFlor_AnemicTwinstipe_01"] = {
    "DetectAnimal",
    "DrainFatigue",
    "Invisibility",
  },
  ["TR_m7_NVA8_IngCrea_GoatPelt_01"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Agility" },
    "DetectAnimal",
  },
  ["T_IngFlor_Cabbage_02"] = {
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Intelligence" },
  },
  ["T_IngFood_MeatBoar_02"] = {
    "RestoreFatigue",
    "ResistFrost",
    { "DrainAttribute" , "Agility" },
  },
  ["T_IngFlor_BloodlilyPod_01"] = {
    "DamageFatigue",
    { "RestoreAttribute" , "Intelligence" },
    "DamageHealth",
    "Feather",
  },
  ["TR_m4_ing_rotten_guar_meat"] = {
    "Poison",
    "ResistFrost",
    "WeaknessToPoison",
  },
  ["T_IngFlor_Tanna_01"] = {
    "RestoreFatigue",
    "RestoreMagicka",
    "DrainHealth",
    "WeaknessToCommonDisease",
  },
  ["T_IngFlor_SpongeLotusSeed_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Willpower" },
  },
  ["T_IngFood_Fig_Dried_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
  },
  ["T_IngFlor_PilgrimGel_01"] = {
    "RestoreFatigue",
    "Feather",
    { "DrainAttribute" , "Strength" },
    "Mark",
  },
  ["T_IngFlor_GoldenRod_01"] = {
    { "RestoreAttribute" , "Strength" },
    "WaterBreathing",
    "Silence",
    "Light",
  },
  ["T_IngFlor_Arrowroot_01"] = {
    { "RestoreAttribute" , "Agility" },
    { "DamageAttribute" , "Luck" },
    { "FortifyAttribute" , "Strength" },
    "Burden",
  },
  ["T_IngMine_RubyDeTomb_01"] = {
    "DrainHealth",
    "Feather",
    { "RestoreAttribute" , "Intelligence" },
    { "DrainAttribute" , "Agility" },
  },
  ["T_IngFlor_SomnaliusFrond_01"] = {
    { "RestoreAttribute" , "Speed" },
    { "DamageAttribute" , "Endurance" },
    "FortifyHealth",
    "Feather",
  },
  ["TR_m3_OE_RatMeatPoison"] = {
    "Poison",
    "DamageHealth",
  },
  ["TR_m7_Ns_MG_Hemlock_01"] = {
    "CurePoison",
    "Paralyze",
    "FireDamage",
    "ResistFrost",
  },
  ["TR_m4_AA_SehutuHeart"] = {
    "Dispel",
    "DamageMagicka",
    "DrainFatigue",
    "FortifyAttack",
  },
  ["T_IngFlor_Gloomtear_01"] = {
    { "DrainAttribute" , "Personality" },
    "ResistFire",
    "DamageFatigue",
  },
  ["T_IngCrea_MothWingCyr_02"] = {
    { "DrainAttribute" , "Willpower" },
    "DetectAnimal",
    "FortifyMagicka",
    "ResistMagicka",
  },
  ["T_IngFood_BreadRedguard_01"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Endurance" },
  },
  ["T_IngCrea_SaberCatTooth_01"] = {
    { "RestoreAttribute" , "Strength" },
    "Jump",
    "Invisibility",
    "FortifyAttack",
  },
  ["TR_m3_q_OE_MG_Dae_Gems"] = {
    { "DrainAttribute" , "Willpower" },
    "WaterWalking",
    { "DamageAttribute" , "Endurance" },
    "Sanctuary",
  },
  ["T_IngFlor_Chokeberry_01"] = {
    "Poison",
    "FortifyHealth",
    "DisintegrateWeapon",
  },
  ["T_IngFlor_TempleDome_01"] = {
    "Blind",
    "Burden",
    "Reflect",
    "Shield",
  },
  ["T_IngCrea _StridentBirdFeath_01"] = {
    "DrainFatigue",
    "WeaknessToMagicka",
    "Dispel",
    "Feather",
  },
  ["T_IngFlor_Trefoil_01"] = {
    "WeaknessToFrost",
    "Shield",
    "ResistPoison",
  },
  ["T_IngCrea_MothWingCyr_06"] = {
    "WeaknessToMagicka",
    { "RestoreAttribute" , "Personality" },
    "Paralyze",
    "Sanctuary",
  },
  ["T_IngFlor_Stinkhorn_01"] = {
    "DamageHealth",
    "RestoreMagicka",
    "WaterWalking",
    "Invisibility",
  },
  ["T_IngCrea_LichDust_01"] = {
    "Dispel",
    { "FortifyAttribute" , "Intelligence" },
    "Reflect",
    "StuntedMagicka",
  },
  ["T_IngFood_BreadFlat_02"] = {
    "RestoreHealth",
  },
  ["TR_i3-591_ingred_RaathimAsh"] = {
    { "DrainAttribute" , "Intelligence" },
    "CureCommonDisease",
    "DrainMagicka",
    { "RestoreAttribute" , "Endurance" },
  },
  ["T_IngCrea_ShellMolecrab_01"] = {
    "Shield",
    "DrainMagicka",
    "DrainHealth",
    "ResistShock",
  },
  ["T_IngCrea_Eyestar_01"] = {
    "NightEye",
    "Light",
    "WeaknessToMagicka",
    "WaterBreathing",
  },
  ["T_IngFood_MeatKagouti_01"] = {
    "RestoreFatigue",
    "WeaknessToCommonDisease",
  },
  ["T_IngFood_Grape_01"] = {
    "RestoreFatigue",
    { "DamageAttribute" , "Willpower" },
    "ResistShock",
    { "RestoreAttribute" , "Luck" },
  },
  ["T_IngCrea_ButterflyWingCyr_04"] = {
    { "RestoreAttribute" , "Strength" },
    { "FortifyAttribute" , "Willpower" },
    "ResistShock",
  },
  ["T_IngFlor_RedrosePetal_01"] = {
    { "FortifySkill" , "Speechcraft" },
    "ResistPoison",
    "Paralyze",
    "Jump",
  },
  ["T_IngCrea_SkyrendSlumgum_01"] = {
    { "DrainAttribute" , "Personality" },
    "Poison",
    "WeaknessToFire",
    "Shield",
  },
  ["T_IngMine_Sapphire_01"] = {
    "DamageHealth",
    "Shield",
    "ResistMagicka",
    "DamageFatigue",
  },
  ["T_IngFlor_ArrowrootFlower_01"] = {
    { "RestoreAttribute" , "Agility" },
    { "DamageAttribute" , "Luck" },
    { "FortifySkill" , "Marksman" },
    "NightEye",
  },
  ["T_IngCrea_HorkerPupPelt_02"] = {
    "FrostShield",
    "WeaknessToFire",
    { "DrainAttribute" , "Speed" },
  },
  ["T_IngFlor_RustRussula_01"] = {
    "DrainFatigue",
    "FortifyHealth",
    "Poison",
    { "FortifyAttribute" , "Luck" },
  },
  ["T_IngFlor_BloodlilyFlower_01"] = {
    { "FortifyAttribute" , "Personality" },
    "DamageHealth",
    "FortifyAttack",
    "FireShield",
  },
  ["T_IngCrea_HopperMeat"] = {
    "RestoreFatigue",
    "DetectAnimal",
    "ResistCommonDisease",
    "FortifyHealth",
  },
  ["T_IngCrea_CetaceanMelon"] = {
    "DetectAnimal",
    "Sound",
    { "DamageAttribute" , "Personality" },
    { "FortifySkill" , "Mysticism" },
  },
  ["T_IngMine_PearlBlue_01"] = {
    { "DamageAttribute" , "Intelligence" },
    "WaterBreathing",
    "RestoreMagicka",
    "FortifyMaximumMagicka",
  },
  ["T_IngCrea_SturgeonRoe_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
    "WaterBreathing",
  },
  ["T_IngFood_FishPike_01"] = {
    "RestoreFatigue",
    { "RestoreAttribute" , "Strength" },
  },
  ["T_IngFlor_Wormwood_01"] = {
    "FortifyFatigue",
    "Invisibility",
    "DamageHealth",
    "DamageMagicka",
  },
  ["T_IngFood_SilverPalmfruit_01"] = {
    "RestoreFatigue",
    "ResistParalysis",
    "DetectKey",
    { "DrainAttribute" , "Willpower" },
  },
  ["T_IngFlor_Lazarum_01"] = {
    "DrainHealth",
    { "DrainAttribute" , "Agility" },
    "Blind",
    { "RestoreAttribute" , "Agility" },
  },
  ["T_IngMine_BloodstoneDae_01"] = {
    "RestoreHealth",
    "DamageMagicka",
    "Invisibility",
    { "RestoreAttribute" , "Strength" },
  },
  ["T_IngFlor_BlacksporeCap_01"] = {
    "Burden",
    "RestoreHealth",
    "FortifyHealth",
    "WeaknessToMagicka",
  },
  ["TR_m2_q_38_ashbonemeal"] = {
    { "RestoreAttribute" , "Agility" },
    "Telekinesis",
    "ResistMagicka",
    { "DrainAttribute" , "Personality" },
  },
  ["T_IngFlor_Milkthistle_01"] = {
    "ResistFrost",
    "FortifyHealth",
    { "FortifyAttribute" , "Endurance" },
    "DrainFatigue",
  },
  ["T_IngCrea_Newtscales_01"] = {
    { "DrainAttribute" , "Strength" },
    "ResistPoison",
    { "RestoreAttribute" , "Agility" },
    "SwiftSwim",
  },
  ["TR_m4_TJ_MoonshadowRose"] = {
    { "FortifyAttribute" , "Personality" },
    "NightEye",
    "Sanctuary",
    "WaterBreathing",
  },
  ["T_IngFood_Potato_01"] = {
    "RestoreFatigue",
    "Burden",
  },
  ["T_IngCrea_ArmunHide_01"] = {
    "ResistNormalWeapons",
    "RestoreMagicka",
    "ResistFire",
    "WeaknessToFrost",
  },
  ["T_IngFlor_GreyTickPowder_01"] = {
    { "DrainAttribute" , "Willpower" },
    { "DrainAttribute" , "Intelligence" },
    "FortifyAttack",
  },
  ["T_IngCrea_HorkerPupPelt_03"] = {
    "FrostDamage",
    { "FortifySkill" , "Athletics" },
    { "DrainAttribute" , "Agility" },
  },
  ["T_IngFlor_Hamumroot_01"] = {
    "RestoreFatigue",
    "Sanctuary",
    { "RestoreSkill" , "Restoration" },
    "FortifyHealth",
  },
  ["TR_m7_q_Ns_IC8_gem1"] = {
    { "FortifyAttribute" , "Endurance" },
    "ResistMagicka",
    "WeaknessToMagicka",
    "Levitate",
  },
  ["TR_m2_aztear_i2-383-ind"] = {
    "CureCommonDisease",
    "CureBlightDisease",
    "CurePoison",
  },
  ["T_IngFlor_CFungus_01"] = {
    "Paralyze",
    { "DamageAttribute" , "Intelligence" },
    "WaterBreathing",
    "Burden",
  },
  ["T_IngFood_MeatCliffracer_01"] = {
    "DamageFatigue",
    "Levitate",
    { "DrainAttribute" , "Personality" },
  },
  ["T_IngFlor_Greenstain_01"] = {
    { "DrainAttribute" , "Speed" },
    "Levitate",
    { "DrainAttribute" , "Agility" },
    "DrainHealth",
  },
  ["T_IngFood_Mokre_01"] = {
    { "DrainAttribute" , "Personality" },
    "Levitate",
    "DrainHealth",
    "Reflect",
  },
  ["T_IngMine_Amethyst_01"] = {
    "ResistPoison",
    "DrainFatigue",
    "CureCommonDisease",
    { "RestoreAttribute" , "Willpower" },
  },
  ["T_IngFlor_MaceFruit_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Endurance" },
    "Shield",
    { "FortifySkill" , "BluntWeapon" },
  },
  ["T_IngFood_FishCod_01"] = {
    "RestoreFatigue",
    "ResistFrost",
  },
  ["T_IngFlor_SheggoShelf_01"] = {
    "NightEye",
    { "DrainAttribute" , "Personality" },
    "Chameleon",
    "ResistPoison",
  },
  ["T_IngSpice_Muscat_01"] = {
    "DrainFatigue",
    "Blind",
    "Levitate",
    "WeaknessToPoison",
  },
  ["T_IngFlor_Shadowfly_02"] = {
    "Blind",
    "NightEye",
    "SlowFall",
    "Feather",
  },
  ["T_IngFlor_DryadSaddle_01"] = {
    { "RestoreAttribute" , "Luck" },
    "ResistFrost",
    { "DamageAttribute" , "Speed" },
    "FrostDamage",
  },
  ["T_IngFlor_RedCoral_01"] = {
    "WaterBreathing",
    "RestoreMagicka",
    "Dispel",
    "Sanctuary",
  },
  ["T_IngCrea_MothWingMw_02"] = {
    "ResistFire",
    { "DrainAttribute" , "Speed" },
    "ResistMagicka",
    "SlowFall",
  },
  ["T_IngFlor_WormWh01"] = {
    "DrainFatigue",
    "NightEye",
    "Feather",
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngCrea_SnowraySting_01"] = {
    "Blind",
    "ResistShock",
    "SwiftSwim",
  },
  ["T_IngCrea_KwoomFronds"] = {
    "FortifyFatigue",
    { "FortifyAttribute" , "Endurance" },
    "Shield",
    { "DrainAttribute" , "Intelligence" },
  },
  ["T_IngMine_Topaz_01"] = {
    { "DrainAttribute" , "Strength" },
    { "FortifyAttribute" , "Intelligence" },
    "RestoreHealth",
    "FireShield",
  },
  ["T_IngCrea_MeatHoney_01"] = {
    "DamageHealth",
    "FortifyHealth",
    { "DrainAttribute" , "Intelligence" },
    "CureCommonDisease",
  },
  ["T_IngMine_OreSulfur_01"] = {
    { "DamageAttribute" , "Personality" },
    "RestoreHealth",
    { "FortifySkill" , "Alchemy" },
    "FireShield",
  },
  ["T_IngCrea_ThresherClaw_01"] = {
    { "FortifyAttribute" , "Strength" },
    "ResistFire",
    "WeaknessToFrost",
    "NightEye",
  },
  ["T_IngFlor_WtLillyWhite_01"] = {
    "WaterWalking",
    { "DrainAttribute" , "Willpower" },
    "Dispel",
    "Levitate",
  },
  ["T_IngFlor_TigerlilyNectar_01"] = {
    { "RestoreAttribute" , "Endurance" },
    { "DamageAttribute" , "Strength" },
    "WaterWalking",
    { "DamageAttribute" , "Willpower" },
  },
  ["T_IngFlor_Aquilegia_01"] = {
    { "RestoreAttribute" , "Personality" },
    "ResistFrost",
    "DrainMagicka",
    "Chameleon",
  },
  ["T_IngMine_RockCrystalDae_01"] = {
    "Burden",
    "CurePoison",
    { "DrainAttribute" , "Speed" },
    "RestoreMagicka",
  },
  ["TR_m7_q_Ns_IC8_gem7"] = {
    { "DrainAttribute" , "Strength" },
    { "FortifyAttribute" , "Intelligence" },
    "RestoreHealth",
    "FireShield",
  },
  ["T_IngFlor_StJahnsWort_01"] = {
    "ResistShock",
    "DamageHealth",
    "CurePoison",
    "Chameleon",
  },
  ["T_IngCrea_SpiderSilk_01"] = {
    "SlowFall",
    "Paralyze",
    "Invisibility",
    { "DrainAttribute" , "Speed" },
  },
  ["T_IngMine_Agate_02"] = {
    "FireShield",
    "WeaknessToNormalWeapons",
    "FortifyAttack",
  },
  ["T_IngFlor_Bluefoot_01"] = {
    "DrainFatigue",
    "WaterWalking",
    "Poison",
    "Dispel",
  },
  ["T_IngFlor_SaltCrocusPetal_01"] = {
    "Paralyze",
    "ResistShock",
    "ResistPoison",
    "DrainFatigue",
  },
  ["T_IngSpice_Drumpear_01"] = {
    { "RestoreAttribute" , "Luck" },
    "FireShield",
    "RestoreFatigue",
  },
  ["T_IngSpice_Cinnamon_01"] = {
    "FireDamage",
    { "RestoreSkill" , "Destruction" },
    "DamageFatigue",
  },
  ["TR_m1_q67_Fa1_Seeds"] = {
    "Poison",
    "Silence",
  },
  ["T_IngMine_DiamondDeTomb_01"] = {
    { "DrainAttribute" , "Agility" },
    "Invisibility",
    "Reflect",
    "DetectKey",
  },
  ["T_IngCrea_ButterflyWingSky_03"] = {
    { "FortifyAttribute" , "Endurance" },
    "WeaknessToShock",
    "FireShield",
    "DetectEnchantment",
  },
  ["T_IngCrea_BarkHeart_01"] = {
    "NightEye",
    { "RestoreAttribute" , "Willpower" },
    "DrainMagicka",
    "RestoreFatigue",
  },
  ["T_IngMine_DiamondBlue_01"] = {
    { "DrainAttribute" , "Intelligence" },
    "Invisibility",
    "Reflect",
    "ResistFrost",
  },
  ["TR_m7_q_Ns_IC8_gem9"] = {
    { "DrainAttribute" , "Willpower" },
    "Burden",
    "ResistParalysis",
    { "FortifyAttribute" , "Personality" },
  },
  ["T_IngFood_Pomegranate_01"] = {
    "RestoreFatigue",
    "RestoreMagicka",
    "Silence",
  },
  ["T_IngCrea_WormmouthHide_01"] = {
    { "DamageAttribute" , "Strength" },
    "ResistPoison",
    "Shield",
    "ResistShock",
  },
  ["TR_m7_Kalk_Orc_Flesh"] = {
    { "FortifyAttribute" , "Strength" },
    { "DrainAttribute" , "Intelligence" },
    { "DrainAttribute" , "Personality" },
  },
  ["T_IngFlor_RedGreenPepper_01"] = {
    "RestoreFatigue",
    "FireDamage",
    { "FortifyAttribute" , "Strength" },
  },
  ["T_IngFlor_BorealHydnum_01"] = {
    "ResistFire",
    "WeaknessToCommonDisease",
    "Feather",
    "Paralyze",
  },
  ["T_IngMine_Spinel_01"] = {
    "WeaknessToMagicka",
    "CureParalyzation",
    "Dispel",
    "DamageHealth",
  },
  ["TR_m3_q_A5_SmuggledEbony"] = {
    { "DrainAttribute" , "Agility" },
    "CurePoison",
    "FrostShield",
    { "RestoreAttribute" , "Speed" },
  },
  ["T_IngFlor_SwmpChal_01"] = {
    { "RestoreAttribute" , "Intelligence" },
    "DamageMagicka",
    "DetectKey",
    { "DrainAttribute" , "Personality" },
  },
  ["T_IngFood_Honey_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Agility" },
    { "FortifyAttribute" , "Speed" },
    "CureCommonDisease",
  },
  ["TR_m2_q_9_BGPetals"] = {
    { "RestoreAttribute" , "Intelligence" },
    "Invisibility",
    { "DrainAttribute" , "Endurance" },
    "DrainMagicka",
  },
  ["TR_m7_q_guarliver"] = {
    "DamageMagicka",
    { "DrainAttribute" , "Agility" },
    "RestoreFatigue",
  },
  ["T_IngCrea_DridreaSilk_01"] = {
    "Burden",
    "NightEye",
    "Chameleon",
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngFlor_MarasBeads_01"] = {
    "FortifyHealth",
    "ResistPoison",
    "Feather",
    "WeaknessToFire",
  },
  ["T_IngCrea_AebisFeathers_01"] = {
    "Sound",
    "Levitate",
    "ResistParalysis",
  },
  ["TR_m3_q_A9_rewardemerald"] = {
    "FortifyMagicka",
    "RestoreHealth",
    { "DrainAttribute" , "Agility" },
    { "DrainAttribute" , "Endurance" },
  },
  ["TR_m2_q_38_purebonemeal"] = {
    { "RestoreAttribute" , "Agility" },
    "Telekinesis",
    "DrainFatigue",
    { "DrainAttribute" , "Personality" },
  },
  ["T_IngFood_EggOrnada_01"] = {
    "RestoreFatigue",
    "Poison",
    "CurePoison",
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngCrea_OrcBlood_01"] = {
    { "DrainAttribute" , "Speed" },
    { "FortifyAttribute" , "Strength" },
    "Shield",
    "DrainMagicka",
  },
  ["T_IngMine_OreCopper_01"] = {
    { "DrainAttribute" , "Willpower" },
    "WeaknessToFire",
    "ResistCommonDisease",
    "Telekinesis",
  },
  ["T_IngFood_GrapeWrothgarian_01"] = {
    "RestoreFatigue",
    "DrainMagicka",
    "ResistFrost",
    { "FortifyAttribute" , "Intelligence" },
  },
  ["T_IngFlor_CinnabarPolypore_01"] = {
    { "RestoreAttribute" , "Agility" },
    { "DamageAttribute" , "Endurance" },
    "SpellAbsorption",
    { "DamageAttribute" , "Personality" },
  },
  ["T_IngCrea_Silk_01"] = {
    "DrainMagicka",
    "DetectEnchantment",
    "Dispel",
    "DetectAnimal",
  },
  ["T_IngCrea_ButterflyWingSky_04"] = {
    "Feather",
    "DrainMagicka",
    "Jump",
    "Silence",
  },
  ["T_IngFlor_Mindcap_01"] = {
    "Sound",
    "FortifyMagicka",
    "DrainFatigue",
    "Poison",
  },
  ["T_IngMine_PearlPink_01"] = {
    { "DrainAttribute" , "Strength" },
    "WaterBreathing",
    { "FortifySkill" , "Restoration" },
    "RestoreHealth",
  },
  ["T_IngFood_Carrot_01"] = {
    "RestoreFatigue",
    { "DamageAttribute" , "Willpower" },
    { "RestoreAttribute" , "Intelligence" },
    "NightEye",
  },
  ["T_IngMine_IceCrystal_01"] = {
    "WeaknessToFrost",
    "FrostDamage",
    "FrostShield",
    "ResistFrost",
  },
  ["T_IngCrea_Ambergris_float"] = {
    "DrainMagicka",
    { "FortifyAttribute" , "Personality" },
    "Reflect",
    "DetectEnchantment",
  },
  ["T_IngCrea_Starfish_02"] = {
    "WaterBreathing",
    "WeaknessToPoison",
    { "FortifySkill" , "Athletics" },
    "Chameleon",
  },
  ["T_IngCrea_ButterflyWingCyr_06"] = {
    "FortifyMagicka",
    "ResistMagicka",
    "Silence",
    { "DamageAttribute" , "Strength" },
  },
  ["T_IngCrea_Starfish_03"] = {
    "WaterBreathing",
    "WeaknessToFrost",
    "RestoreMagicka",
    "Feather",
  },
  ["T_IngFlor_SeaCup_01"] = {
    "Burden",
    "WaterBreathing",
    "DrainFatigue",
    "NightEye",
  },
  ["T_IngFood_MarmongPaste_01"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Intelligence" },
  },
  ["T_IngCrea_GoatPelt_01"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Agility" },
    "DetectAnimal",
  },
  ["T_IngCrea_Wool_01"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Agility" },
    "ResistFrost",
    "DetectAnimal",
  },
  ["TR_m3_q_OE_MG_Dae_Sapphire"] = {
    "Dispel",
    "NightEye",
  },
  ["TR_m3_OE_TG_Vomit"] = {
    "Poison",
    "Paralyze",
    "ResistPoison",
    "CurePoison",
  },
  ["T_IngMine_OreQuicksilver_01"] = {
    "DamageHealth",
    "Reflect",
    "Blind",
    "Poison",
  },
  ["T_IngFlor_WispStalk_01"] = {
    "DamageHealth",
    "Chameleon",
    { "FortifyAttribute" , "Speed" },
    "Silence",
  },
  ["T_IngFood_FishLongfinFilet_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Speed" },
    "DrainMagicka",
    "FortifyFatigue",
  },
  ["T_IngFlor_SmearSpores_01"] = {
    "Blind",
    "Poison",
    "DamageFatigue",
    "WaterBreathing",
  },
  ["T_IngMine_GarnetDae_01"] = {
    "WeaknessToNormalWeapons",
    "DrainFatigue",
    "CurePoison",
    { "FortifyAttribute" , "Personality" },
  },
  ["T_IngFood_Gooseb01"] = {
    "RestoreFatigue",
    "WaterBreathing",
    { "DrainAttribute" , "Intelligence" },
    "DrainMagicka",
  },
  ["T_IngCrea_MeatDark_01"] = {
    "RestoreHealth",
  },
  ["T_IngFood_MeatHam_01"] = {
    "FortifyFatigue",
    { "FortifyAttribute" , "Strength" },
  },
  ["T_IngFlor_Mistletoe_01"] = {
    "Dispel",
    "ResistMagicka",
    "DamageHealth",
    "CureBlightDisease",
  },
  ["T_IngFood_Siyat_02"] = {
    "FortifyFatigue",
  },
  ["T_IngFlor_DrumpearSeeds_01"] = {
    { "FortifyAttribute" , "Luck" },
    "ResistFire",
    "Sound",
    "Paralyze",
  },
  ["T_IngFood_TeaAltmer_02"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Endurance" },
    "FortifyFatigue",
    { "DamageAttribute" , "Speed" },
  },
  ["T_IngMine_Garnet_01"] = {
    "WeaknessToNormalWeapons",
    "DrainFatigue",
    "CurePoison",
    { "FortifyAttribute" , "Personality" },
  },
  ["T_IngMine_Arsenic_01"] = {
    "Poison",
    "DamageHealth",
    { "FortifyAttribute" , "Personality" },
    "DrainHealth",
  },
  ["T_IngMine_OreZinc_01"] = {
    "NightEye",
    "CureCommonDisease",
    "SpellAbsorption",
    { "FortifyAttribute" , "Endurance" },
  },
  ["T_IngCrea_HopperAntler_01"] = {
    "Jump",
    { "DamageAttribute" , "Personality" },
    "ResistParalysis",
  },
  ["T_IngMine_Agate_04"] = {
    "Burden",
    "SlowFall",
    "Light",
    "Reflect",
  },
  ["T_IngMine_OreGoldDae_01"] = {
    { "DrainAttribute" , "Willpower" },
    "Burden",
    "ResistParalysis",
    { "FortifyAttribute" , "Personality" },
  },
  ["T_IngMine_Aquamarine_01"] = {
    "DrainHealth",
    "CurePoison",
    "WaterBreathing",
    "WeaknessToFrost",
  },
  ["T_IngFlor_Trollroot_01"] = {
    "Poison",
    "FortifyAttack",
    "WeaknessToFire",
    "CureParalyzation",
  },
  ["T_IngFood_FishSalmon_01"] = {
    "RestoreFatigue",
    { "RestoreAttribute" , "Endurance" },
  },
  ["T_IngCrea_RocEgg_01"] = {
    "Burden",
    "FortifyMagicka",
    "SpellAbsorption",
    "Shield",
  },
  ["T_IngFlor_Spiddal_01"] = {
    "DamageHealth",
    "DamageMagicka",
    "FireDamage",
    "RestoreFatigue",
  },
  ["T_IngFlor_Cupling_01"] = {
    "DamageHealth",
    "WeaknessToCommonDisease",
    "Silence",
    { "FortifySkill" , "Alchemy" },
  },
  ["T_IngCrea_MothWingCyr_05"] = {
    "Dispel",
    "DamageMagicka",
    "DetectAnimal",
    "Telekinesis",
  },
  ["TR_m4_AA_Tomb_2_Emerald"] = {
    "FortifyMagicka",
    "RestoreHealth",
    { "DrainAttribute" , "Agility" },
    { "DrainAttribute" , "Endurance" },
  },
  ["T_IngFlor_DarkSage_01"] = {
    "CureParalyzation",
    { "RestoreAttribute" , "Agility" },
    "DrainMagicka",
    "WeaknessToPoison",
  },
  ["T_IngFlor_PilgrimPetals_01"] = {
    "RestoreFatigue",
    "Feather",
    { "DrainAttribute" , "Strength" },
    "Recall",
  },
  ["T_IngCrea_MothWingCyr_04"] = {
    "DetectKey",
    "Poison",
    "FortifyAttack",
    "SpellAbsorption",
  },
  ["T_IngCrea_StridentBirdFeath_01"] = {
    "DrainFatigue",
    "WeaknessToMagicka",
    "Dispel",
    "Feather",
  },
  ["T_IngCrea _SnowraySting_01"] = {
    "Blind",
    "ResistShock",
    "SwiftSwim",
  },
  ["T_IngMine_Tektite_01"] = {
    "DamageHealth",
    "Paralyze",
    "Reflect",
    { "DrainAttribute" , "Endurance" },
  },
  ["T_IngFlor_Harrada_01"] = {
    "DamageHealth",
    "DamageFatigue",
    "Silence",
    "Paralyze",
  },
  ["T_IngSpice_Cardamon_01"] = {
    "WeaknessToMagicka",
    "RestoreHealth",
    { "DrainAttribute" , "Willpower" },
    "ResistCommonDisease",
  },
  ["TR_m7_q_Ns_IC8_gem5"] = {
    "ResistPoison",
    "DrainFatigue",
    "CureCommonDisease",
    { "RestoreAttribute" , "Willpower" },
  },
  ["T_IngCrea_EyestarDae_01"] = {
    "NightEye",
    "Light",
    "WeaknessToMagicka",
    "WaterBreathing",
  },
  ["T_IngFood_MeatDolphin_01"] = {
    "RestoreFatigue",
    "SwiftSwim",
    { "FortifySkill" , "Acrobatics" },
    "Jump",
  },
  ["T_IngMine_LapisLazuli_01"] = {
    { "DamageAttribute" , "Speed" },
    "ShockDamage",
    { "RestoreAttribute" , "Speed" },
    "ResistParalysis",
  },
  ["T_IngDye_ImperialPurple_01"] = {
    { "FortifyAttribute" , "Personality" },
    "DivineIntervention",
    "Shield",
  },
  ["TR_m7_q_Ns_IC8_gem8"] = {
    { "DrainAttribute" , "Personality" },
    "LightningShield",
    "WeaknessToFire",
    "ResistShock",
  },
  ["T_IngFlor_LotusPoppyHead_01"] = {
    { "DrainAttribute" , "Willpower" },
    "DamageFatigue",
    "Poison",
    "Invisibility",
  },
  ["T_IngFood_Apple_01"] = {
    "RestoreFatigue",
    { "DamageAttribute" , "Luck" },
    { "FortifyAttribute" , "Willpower" },
  },
  ["TR_m3_nelyn_cursed_pearl"] = {
    { "DrainAttribute" , "Agility" },
    "Dispel",
    "WaterBreathing",
    "ResistCommonDisease",
  },
  ["T_IngFlor_OrangeMoss_01"] = {
    { "FortifyAttribute" , "Endurance" },
    { "FortifyAttribute" , "Agility" },
    "CureCommonDisease",
    "DrainMagicka",
  },
  ["T_IngFlor_FlyAmanita_01"] = {
    "DrainHealth",
    { "FortifyAttribute" , "Luck" },
    { "DrainAttribute" , "Willpower" },
    "Levitate",
  },
  ["T_IngFlor_Dragynia_01"] = {
    { "DrainAttribute" , "Willpower" },
    { "FortifyAttribute" , "Agility" },
    "ResistFire",
    "SpellAbsorption",
  },
  ["TR_m2_q_38_ectoplasm"] = {
    { "FortifyAttribute" , "Agility" },
    "DetectAnimal",
    { "DrainAttribute" , "Strength" },
    "DrainHealth",
  },
  ["T_IngFlor_Taragetis_01"] = {
    { "RestoreAttribute" , "Agility" },
    "Sanctuary",
    { "FortifyAttribute" , "Luck" },
    "RestoreMagicka",
  },
  ["T_IngCrea_EmbalmingPaste_01"] = {
    "DamageFatigue",
    "ResistCommonDisease",
    { "FortifySkill" , "Conjuration" },
    "SpellAbsorption",
  },
  ["T_IngFood_CheeseNord_01"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Strength" },
    { "DrainAttribute" , "Speed" },
  },
  ["T_IngCrea_SeaUrchinMeat_01"] = {
    { "FortifyAttribute" , "Endurance" },
    { "DamageAttribute" , "Agility" },
    "SwiftSwim",
  },
  ["T_IngSpice_Nigella_01"] = {
    "ResistCommonDisease",
    { "DrainAttribute" , "Agility" },
    { "RestoreAttribute" , "Willpower" },
  },
  ["T_IngSpice_Pepper_01"] = {
    { "DrainAttribute" , "Personality" },
    "ResistMagicka",
    "FireDamage",
  },
  ["T_IngCrea_MothWingSky_01"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Strength" },
    { "RestoreAttribute" , "Strength" },
  },
  ["T_IngMine_CaputMortuum_01"] = {
    "Blind",
    { "FortifySkill" , "Alchemy" },
    "Chameleon",
  },
  ["T_IngMine_OreTin_01"] = {
    "ResistCommonDisease",
    { "FortifyAttribute" , "Endurance" },
    "FortifyAttack",
    "Burden",
  },
  ["TR_m1_Q_Ingred_BlackRose"] = {
    { "FortifyAttribute" , "Personality" },
    "DrainFatigue",
    "Poison",
    "Invisibility",
  },
  ["T_IngFlor_Ashdew_01"] = {
    { "FortifyAttribute" , "Agility" },
    { "DrainAttribute" , "Intelligence" },
    "DrainMagicka",
    "DrainFatigue",
  },
  ["TR_m7_Ns_JNS_3_TombAD"] = {
    { "FortifyAttribute" , "Agility" },
    { "DrainAttribute" , "Intelligence" },
    "DrainMagicka",
    "DrainFatigue",
  },
  ["TR_m7_NVA8_snowbear_pelt"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Speed" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["T_IngCrea_BearpeltBlack_01"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Strength" },
    "WeaknessToFrost",
    "DetectAnimal",
  },
  ["T_IngCrea_BarkScale_01"] = {
    "SlowFall",
    "WeaknessToFire",
  },
  ["T_IngCrea_Jadescales_01"] = {
    "DamageMagicka",
    { "FortifySkill" , "Athletics" },
    { "FortifyAttribute" , "Luck" },
    "Chameleon",
  },
  ["T_IngCrea_RedoranHoundChitin_01"] = {
    { "DrainAttribute" , "Agility" },
    "DetectKey",
    { "RestoreAttribute" , "Speed" },
    "DamageHealth",
  },
  ["T_IngFood_PastryFrRedguard_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
    "Silence",
  },
  ["TR_m7_q_Ns_IC8_gem3"] = {
    "FortifyMagicka",
    "RestoreHealth",
    { "DrainAttribute" , "Agility" },
    { "DrainAttribute" , "Endurance" },
  },
  ["T_IngMine_OreBitterstone_01"] = {
    { "DrainAttribute" , "Willpower" },
    "WeaknessToFire",
    "ResistCommonDisease",
    "Telekinesis",
  },
  ["T_IngFood_MeatArenthJerky_01"] = {
    "RestoreFatigue",
    "ResistPoison",
  },
  ["T_IngCrea_Spikeworm_01"] = {
    "DrainFatigue",
    "Burden",
    "ResistNormalWeapons",
    "Light",
  },
  ["T_IngCrea_ButterflyWingSky_01"] = {
    { "FortifyAttribute" , "Luck" },
    { "FortifyAttribute" , "Speed" },
    "WeaknessToFrost",
    "WeaknessToPoison",
  },
  ["T_IngFlor_Elfcup_01"] = {
    { "DamageAttribute" , "Willpower" },
    "CureCommonDisease",
    { "FortifyAttribute" , "Strength" },
    { "DamageAttribute" , "Intelligence" },
  },
  ["T_IngFlor_LotusSeed_01"] = {
    "DamageHealth",
    "ResistMagicka",
    "Feather",
    "Dispel",
  },
  ["T_IngFlor_BertpodSlice_01"] = {
    "ResistFire",
    "Blind",
    "DamageMagicka",
    "RestoreFatigue",
  },
  ["T_IngDye_Ultramarine_01"] = {
    "WeaknessToShock",
    "WaterBreathing",
    "SwiftSwim",
    { "FortifyAttribute" , "Personality" },
  },
  ["T_IngCrea_AspisGland"] = {
    "Poison",
    "DamageFatigue",
    { "FortifyAttribute" , "Luck" },
    "DetectKey",
  },
  ["T_IngFlor_Hamumroot_02"] = {
    "RestoreFatigue",
    "Sanctuary",
    "RestoreHealth",
    "FortifyHealth",
  },
  ["T_IngCrea_KoboldTongue_01"] = {
    "WaterBreathing",
    "Paralyze",
    "RestoreHealth",
    "ResistParalysis",
  },
  ["T_IngCrea_AtavisticEye_01"] = {
    "DetectAnimal",
    "Blind",
    { "FortifyAttribute" , "Luck" },
    "WeaknessToFire",
  },
  ["T_IngFood_FishBrowntrout_01"] = {
    "RestoreFatigue",
    "ResistCommonDisease",
  },
  ["T_IngFlor_Clawdooie_01"] = {
    "RestoreFatigue",
    "WeaknessToNormalWeapons",
    { "FortifyAttribute" , "Intelligence" },
    "FortifyAttack",
  },
  ["T_IngCrea_KwoomEgg_01"] = {
    "RestoreFatigue",
    "Silence",
    { "FortifyAttribute" , "Endurance" },
  },
  ["T_IngFlor_AloeVeraPulp_01"] = {
    "ResistFire",
    "WeaknessToMagicka",
    "NightEye",
    "CurePoison",
  },
  ["T_IngFlor_DesrosePetal_01"] = {
    { "RestoreAttribute" , "Intelligence" },
    "FortifyMagicka",
    { "DrainAttribute" , "Speed" },
    { "FortifyAttribute" , "Willpower" },
  },
  ["T_IngFlor_VeiledUrnula_01"] = {
    "DamageFatigue",
    "Blind",
    "Sanctuary",
    { "DamageAttribute" , "Strength" },
  },
  ["T_IngFood_Snowberry_01"] = {
    { "RestoreAttribute" , "Personality" },
    "DamageFatigue",
    { "DrainAttribute" , "Agility" },
    "FrostShield",
  },
  ["T_IngCrea_FrogEye_01"] = {
    { "FortifyAttribute" , "Intelligence" },
    "DrainMagicka",
    "WaterBreathing",
    "SpellAbsorption",
  },
  ["PC_m1_Gld_ClaudiusFlax"] = {
    "FortifyFatigue",
    { "FortifySkill" , "LightArmor" },
    "WeaknessToFire",
    "FrostShield",
  },
  ["T_IngFlor_Indulcet_01"] = {
    { "FortifyAttribute" , "Personality" },
    "RestoreFatigue",
    "Sanctuary",
    { "DamageAttribute" , "Agility" },
  },
  ["T_IngCrea_SkyrendQStinger_01"] = {
    "Poison",
    "Paralyze",
    "ResistParalysis",
    "ResistPoison",
  },
  ["TR_m7_AHPicnicCrabMeat"] = {
    "RestoreFatigue",
    "ResistShock",
    "LightningShield",
    { "RestoreAttribute" , "Luck" },
  },
  ["T_IngFlor_ZukomaBlossom_01"] = {
    { "DamageAttribute" , "Agility" },
    "Jump",
    { "FortifyAttribute" , "Luck" },
    { "FortifySkill" , "Acrobatics" },
  },
  ["T_IngFlor_MonkshoodRootPulp_01"] = {
    { "RestoreAttribute" , "Strength" },
    { "DamageAttribute" , "Intelligence" },
    { "FortifyAttribute" , "Endurance" },
    "Burden",
  },
  ["T_IngFlor_YamOrb_01"] = {
    "Light",
    { "RestoreAttribute" , "Endurance" },
    "FortifyFatigue",
    "WeaknessToMagicka",
  },
  ["T_IngMine_OreBrass_01"] = {
    "FortifyHealth",
    "WeaknessToNormalWeapons",
    "Jump",
  },
  ["T_IngMine_PearlPinkDae_01"] = {
    { "DrainAttribute" , "Strength" },
    "WaterBreathing",
    { "FortifySkill" , "Restoration" },
    "RestoreHealth",
  },
  ["T_IngFlor_Orcscrown"] = {
    "Poison",
    "ResistNormalWeapons",
    { "FortifyAttribute" , "Agility" },
  },
  ["T_IngFlor_LichenBlue_01"] = {
    { "FortifyAttribute" , "Intelligence" },
    "ResistMagicka",
    { "DrainAttribute" , "Strength" },
    "WeaknessToCommonDisease",
  },
  ["TR_m7_NVA8_ingred_wolf_pelt"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Speed" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["T_IngFlor_Cornflower_01"] = {
    { "DrainAttribute" , "Personality" },
    { "RestoreAttribute" , "Endurance" },
    { "DrainAttribute" , "Luck" },
    "ResistShock",
  },
  ["T_IngFlor_GhostLaurel"] = {
    "WeaknessToMagicka",
    "WeaknessToFrost",
    "Sanctuary",
    "Chameleon",
  },
  ["T_IngFlor_InkCone_01"] = {
    "Blind",
    "CureParalyzation",
    { "RestoreAttribute" , "Agility" },
    { "DrainAttribute" , "Speed" },
  },
  ["T_IngFlor_Bitterstar_01"] = {
    "RestoreFatigue",
    "FortifyHealth",
    { "DrainAttribute" , "Willpower" },
    "WeaknessToPoison",
  },
  ["T_IngCrea_FrostTrollPelt_01"] = {
    "ResistFrost",
    "WeaknessToFire",
    { "FortifyAttribute" , "Strength" },
    "RestoreHealth",
  },
  ["T_IngMine_Agate_03"] = {
    "NightEye",
    "FortifyMagicka",
    "WeaknessToFire",
    "CurePoison",
  },
  ["TR_m3_TT_Dis_marshrootincense"] = {
    "WeaknessToFire",
    "DrainFatigue",
    "Jump",
    { "FortifyAttribute" , "Personality" },
  },
  ["TR_m1_Q_Ingred_NobleSedge"] = {
    "DamageHealth",
    { "RestoreAttribute" , "Agility" },
    "Poison",
    { "FortifyAttribute" , "Agility" },
  },
  ["T_IngCrea_Minotaurhorn_01"] = {
    "DrainHealth",
    "FortifyAttack",
    "ResistNormalWeapons",
    "FortifyHealth",
  },
  ["T_IngMine_Opal_01"] = {
    "DrainHealth",
    { "DamageAttribute" , "Luck" },
    "Chameleon",
    { "FortifyAttribute" , "Intelligence" },
  },
  ["T_IngFood_Strawberry_01"] = {
    "RestoreFatigue",
    { "DamageAttribute" , "Willpower" },
    "DrainHealth",
    "CurePoison",
  },
  ["T_IngFood_CheeseColovian_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Agility" },
    "ResistParalysis",
  },
  ["T_IngMine_PearlDeTomb_01"] = {
    { "DrainAttribute" , "Agility" },
    "Dispel",
    "WaterBreathing",
    "ResistCommonDisease",
  },
  ["TR_m7_NVA8_boar_leather"] = {
    "Blind",
    "FrostDamage",
    "ResistFrost",
    "Recall",
  },
  ["T_IngFood_Fig_01"] = {
    "RestoreFatigue",
    "ResistCommonDisease",
  },
  ["TR_m1_Ingred_Opal_i62"] = {
    "DrainFatigue",
    "DrainHealth",
    "Light",
  },
  ["T_IngSpice_Curcuma_01"] = {
    "RestoreFatigue",
    "WeaknessToFire",
    { "DamageAttribute" , "Strength" },
    "ResistParalysis",
  },
  ["T_IngFood_MeatBeef_01"] = {
    "RestoreFatigue",
    "FortifyHealth",
  },
  ["T_IngMine_Rockcrystal_01"] = {
    "Burden",
    "CurePoison",
    { "DrainAttribute" , "Speed" },
    "RestoreMagicka",
  },
  ["T_IngDye_Vermilion_01"] = {
    "ResistFire",
    { "FortifyAttribute" , "Personality" },
    "SlowFall",
  },
  ["T_IngFlor_PBloomBulb_01"] = {
    "Poison",
    "Reflect",
    "DamageFatigue",
    "Light",
  },
  ["T_IngFlor_HoneyLily_01"] = {
    "RestoreFatigue",
    "CurePoison",
    "RestoreHealth",
    "WeaknessToMagicka",
  },
  ["T_IngCrea_StridentBirdEgg_01"] = {
    "RestoreFatigue",
    "WeaknessToMagicka",
    "Light",
  },
  ["T_IngFlor_GingerRoot"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Endurance" },
  },
  ["T_IngCrea_CaveTrollEar_01"] = {
    "DetectAnimal",
    "WeaknessToFire",
    { "FortifyAttribute" , "Agility" },
    { "DrainAttribute" , "Intelligence" },
  },
  ["TR_m3_i3_413_white clay"] = {
    { "RestoreAttribute" , "Agility" },
    "Telekinesis",
    "DrainFatigue",
    { "DrainAttribute" , "Personality" },
  },
  ["T_IngFlor_WtLillyPurple_01"] = {
    "WaterWalking",
    { "DrainAttribute" , "Intelligence" },
    "Reflect",
    "WaterBreathing",
  },
  ["T_IngFlor_HoneyLily_02"] = {
    "CurePoison",
    "Paralyze",
    "SlowFall",
  },
  ["T_IngSpice_Pricklespice_01"] = {
    "ShockDamage",
    "DamageFatigue",
    { "FortifyAttribute" , "Endurance" },
    "FortifyHealth",
  },
  ["T_IngFlor_Bloodgrass_01"] = {
    "Chameleon",
    "ResistParalysis",
    "Burden",
    "FortifyHealth",
  },
  ["T_IngCrea_BarracudaTailfin_01"] = {
    "DrainHealth",
    "ResistPoison",
    { "FortifyAttribute" , "Speed" },
    "SwiftSwim",
  },
  ["T_IngFlor_GingerFlower"] = {
    "ResistFire",
    "DrainMagicka",
    { "FortifyAttribute" , "Willpower" },
    { "DrainAttribute" , "Speed" },
  },
  ["T_IngFlor_WidowkissPowder_01"] = {
    "Sanctuary",
    { "DamageAttribute" , "Luck" },
    { "FortifySkill" , "Conjuration" },
    "WeaknessToMagicka",
  },
  ["T_IngFood_MeatParastylus_01"] = {
    "RestoreFatigue",
    "CureParalyzation",
    { "DamageAttribute" , "Endurance" },
    "Paralyze",
  },
  ["T_IngFlor_Oleander_01"] = {
    { "DrainAttribute" , "Strength" },
    "WaterWalking",
    "Poison",
    { "RestoreAttribute" , "Agility" },
  },
  ["T_IngFlor_RedrosePetalDae_01"] = {
    { "FortifySkill" , "Speechcraft" },
    "ResistPoison",
    "Paralyze",
    "Jump",
  },
  ["T_IngMine_RoseQuartz_01"] = {
    "RestoreHealth",
    { "FortifyAttribute" , "Personality" },
    "CureParalyzation",
    "Sound",
  },
  ["T_IngFlor_SummerBolete_01"] = {
    { "RestoreAttribute" , "Agility" },
    "Shield",
    { "DamageAttribute" , "Personality" },
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngCrea_ButterflyWingSky_02"] = {
    "Feather",
    "DrainHealth",
    "Chameleon",
    "Sanctuary",
  },
  ["T_IngFood_NoodlesEsriWheat_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
  },
  ["T_IngFood_Ironrye_01"] = {
    "RestoreFatigue",
    "DrainMagicka",
    { "DamageAttribute" , "Agility" },
    "FortifyHealth",
  },
  ["T_IngCrea_Pearlessence_01"] = {
    "Blind",
    "DrainFatigue",
    "Mark",
    "SpellAbsorption",
  },
  ["T_IngFlor_Peony_01"] = {
    { "RestoreAttribute" , "Strength" },
    "DamageHealth",
    { "DamageAttribute" , "Speed" },
    "RestoreFatigue",
  },
  ["T_IngFlor_EmeticRussula_01"] = {
    { "RestoreAttribute" , "Agility" },
    "Shield",
    { "DamageAttribute" , "Personality" },
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngFlor_Thungleweed_01"] = {
    "WeaknessToPoison",
    { "RestoreAttribute" , "Endurance" },
    "FortifyMagicka",
    "RestoreHealth",
  },
  ["T_IngFlor_CloudedFunnel_01"] = {
    { "RestoreAttribute" , "Intelligence" },
    { "FortifyAttribute" , "Intelligence" },
    { "DamageAttribute" , "Endurance" },
    "DamageMagicka",
  },
  ["T_IngCrea_MothWingSky_02"] = {
    "Burden",
    "FortifyFatigue",
    { "DrainAttribute" , "Endurance" },
    "CureParalyzation",
  },
  ["T_IngFlor_Bleakstar_01"] = {
    "Blind",
    "Light",
    "NightEye",
    "Dispel",
  },
  ["T_IngFlor_GoldWatcSeed_01"] = {
    { "RestoreAttribute" , "Willpower" },
    "NightEye",
    { "FortifySkill" , "Conjuration" },
    "Blind",
  },
  ["T_IngMine_Spellstone_01"] = {
    "DamageFatigue",
    "SpellAbsorption",
    "RestoreMagicka",
    "Telekinesis",
  },
  ["T_IngFlor_Siyat_01"] = {
    "RestoreFatigue",
    "ResistParalysis",
    "DamageMagicka",
    "Dispel",
  },
  ["T_IngMine_OpalDae_01"] = {
    "DrainHealth",
    { "DamageAttribute" , "Luck" },
    "Chameleon",
    { "FortifyAttribute" , "Intelligence" },
  },
  ["TR_m3_q_kwamasmuggle"] = {
    "RestoreFatigue",
    "Paralyze",
    "FrostShield",
    "FortifyHealth",
  },
  ["T_IngCrea_ShellMolecrab_02"] = {
    "Shield",
    "DrainMagicka",
    "DrainHealth",
    "Sanctuary",
  },
  ["T_IngCrea_Dragonscales_01"] = {
    "DamageHealth",
    "ResistPoison",
    "FireShield",
    "Silence",
  },
  ["T_IngFlor_PLotusLeaf_01"] = {
    "Dispel",
  },
  ["T_IngFood_TrinityFruit_01"] = {
    { "DrainAttribute" , "Luck" },
    "ResistFire",
    "WeaknessToPoison",
    "RestoreHealth",
  },
  ["T_IngMine_TurquoiseDae_01"] = {
    { "DrainAttribute" , "Willpower" },
    "WaterWalking",
    { "DamageAttribute" , "Endurance" },
    "Sanctuary",
  },
  ["T_IngCrea _StridentBirdEgg_01"] = {
    "RestoreFatigue",
    "WeaknessToMagicka",
    "Light",
  },
  ["T_IngFlor_LadysSmock_01"] = {
    { "RestoreAttribute" , "Intelligence" },
    "ResistFire",
    "DamageFatigue",
    "FortifyHealth",
  },
  ["T_IngFlor_LichenWhite_01"] = {
    { "FortifyAttribute" , "Luck" },
    "Blind",
    "ResistParalysis",
    "DrainMagicka",
  },
  ["T_IngFlor_SweetbreadPolypore_01"] = {
    "RestoreFatigue",
    "FireShield",
    { "DrainSkill" , "Mysticism" },
    { "RestoreAttribute" , "Willpower" },
  },
  ["T_IngCrea_ButterflyWingCyr_05"] = {
    { "DrainAttribute" , "Willpower" },
    { "FortifyAttribute" , "Luck" },
    "NightEye",
    "RestoreMagicka",
  },
  ["TR_m1_Q_Topaz_Stationary"] = {
    "FireDamage",
    "ResistMagicka",
    "RestoreHealth",
    "SummonScamp",
  },
  ["TR_m7_NVA8_ingred_bear_pelt"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Strength" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["T_IngFlor_Bottomweed_01"] = {
    "FortifyFatigue",
    "WaterBreathing",
    "Paralyze",
    "CureParalyzation",
  },
  ["T_IngCrea_BezoarStone_01"] = {
    "CurePoison",
    "ResistNormalWeapons",
    "Burden",
  },
  ["T_IngMine_Antimony_01"] = {
    "NightEye",
    "LightningShield",
    "FortifyAttack",
  },
  ["T_IngCrea_YethResin_01"] = {
    { "DamageAttribute" , "Personality" },
    "RestoreHealth",
    "Blind",
    "ResistPoison",
  },
  ["T_IngFood_FishLeaperTail_01"] = {
    "Jump",
    { "DrainAttribute" , "Personality" },
    "ResistCommonDisease",
    "WeaknessToShock",
  },
  ["T_IngMine_Ametrine_01"] = {
    { "FortifyAttribute" , "Endurance" },
    "ResistMagicka",
    "WeaknessToMagicka",
    "Levitate",
  },
  ["T_IngFlor_FlaxFlower_02"] = {
    "FortifyFatigue",
    { "FortifySkill" , "LightArmor" },
    "WeaknessToFire",
    "FireShield",
  },
  ["T_IngSpice_Anise_01"] = {
    { "DrainAttribute" , "Willpower" },
    "CureCommonDisease",
    { "DamageAttribute" , "Intelligence" },
    { "FortifyAttribute" , "Willpower" },
  },
  ["T_IngFood_FishPikeperch_01"] = {
    "RestoreFatigue",
    { "RestoreAttribute" , "Speed" },
  },
  ["T_IngCrea_HagravenFeathers_01"] = {
    "DamageMagicka",
    "FortifyAttack",
    "WeaknessToShock",
    { "FortifySkill" , "Conjuration" },
  },
  ["T_IngFlor_Steelblue_01"] = {
    "RestoreMagicka",
    "FireDamage",
    "ResistFrost",
    "Burden",
  },
  ["T_IngFlor_ForsythiaTrRoots_01"] = {
    "Paralyze",
    { "DrainAttribute" , "Intelligence" },
    "LightningShield",
    "NightEye",
  },
  ["T_IngFlor_CairnBolete_01"] = {
    "RestoreHealth",
    { "DamageAttribute" , "Intelligence" },
    "ResistParalysis",
    "ShockDamage",
  },
  ["T_IngSpice_Hibiscus_01"] = {
    "CureCommonDisease",
    { "DamageAttribute" , "Strength" },
    "CurePoison",
  },
  ["TR_m1_Q_BlackRose_Stationary"] = {
    { "FortifyAttribute" , "Personality" },
    "DrainFatigue",
    "Poison",
    "Invisibility",
  },
  ["T_IngMine_Bloodstone_01"] = {
    "RestoreHealth",
    "DamageMagicka",
    "Invisibility",
    { "RestoreAttribute" , "Strength" },
  },
  ["T_IngFood_MeatMutton_01"] = {
    "RestoreFatigue",
    { "RestoreAttribute" , "Strength" },
  },
  ["T_IngCrea_ShellParastylus_01"] = {
    "Jump",
    "DamageMagicka",
    "Blind",
    { "RestoreAttribute" , "Endurance" },
  },
  ["T_IngFood_BreadFlat_03"] = {
    "RestoreHealth",
  },
  ["T_IngFlor_Hamumroot_03"] = {
    "RestoreFatigue",
    "Sanctuary",
    "RestoreHealth",
    "FortifyHealth",
  },
  ["T_IngFlor_RougeCamillea_01"] = {
    { "DrainAttribute" , "Strength" },
    "ResistPoison",
    "FireShield",
    "WeaknessToFrost",
  },
  ["T_IngFlor_UmberMorchella_01"] = {
    "RestoreHealth",
    "Blind",
    "ResistPoison",
    { "DrainAttribute" , "Agility" },
  },
  ["T_IngMine_SmokyQuartz_01"] = {
    "CurePoison",
    "ResistFire",
    "WeaknessToCommonDisease",
    "ResistShock",
  },
  ["T_IngMine_OrePlatinum_01"] = {
    "Invisibility",
    "DrainFatigue",
    "ResistPoison",
    { "FortifyAttribute" , "Luck" },
  },
  ["T_IngFlor_ThirrineLily_01"] = {
    "WaterBreathing",
    "WeaknessToFrost",
    "SwiftSwim",
    "Chameleon",
  },
  ["T_IngCrea_LamiaHair_01"] = {
    "SwiftSwim",
    { "DrainAttribute" , "Strength" },
    "DetectEnchantment",
    "WaterBreathing",
  },
  ["T_IngFood_AltachiPear_01"] = {
    "RestoreFatigue",
    { "RestoreAttribute" , "Intelligence" },
    { "DamageAttribute" , "Agility" },
  },
  ["T_IngCrea_TwilightMembrane_01"] = {
    "ResistMagicka",
    "Levitate",
    "FortifyAttack",
    "DetectAnimal",
  },
  ["T_IngCrea_MothWingSky_03"] = {
    { "FortifyAttribute" , "Agility" },
    { "DrainAttribute" , "Strength" },
    { "FortifySkill" , "Marksman" },
  },
  ["T_IngFood_BreadKeptu_02"] = {
    "RestoreHealth",
  },
  ["T_IngFood_Leek_01"] = {
    "RestoreFatigue",
    "ResistPoison",
  },
  ["T_IngFood_Mango_01"] = {
    "RestoreFatigue",
    "ResistShock",
    "RestoreHealth",
  },
  ["T_IngFood_MeatSqrl_01"] = {
    "Jump",
    "FortifyHealth",
    "CurePoison",
    "ResistPoison",
  },
  ["T_IngCrea_GoldTanthaBeak_01"] = {
    "ResistParalysis",
    "DamageMagicka",
    "Jump",
    "LightningShield",
  },
  ["T_IngFlor_TigaraFruit_01"] = {
    "WeaknessToPoison",
    { "FortifyAttribute" , "Willpower" },
    "CurePoison",
  },
  ["T_IngFlor_LizardFootExtract_01"] = {
    "DrainHealth",
    "DamageFatigue",
    { "RestoreAttribute" , "Luck" },
    "WeaknessToFrost",
  },
  ["T_IngFlor_KingBolete_01"] = {
    "RestoreFatigue",
    { "RestoreAttribute" , "Agility" },
    "ResistParalysis",
  },
  ["T_IngFlor_Primrose_01"] = {
    { "RestoreAttribute" , "Willpower" },
    { "RestoreAttribute" , "Personality" },
    { "FortifyAttribute" , "Luck" },
    { "DamageAttribute" , "Strength" },
  },
  ["T_IngFood_BreadColovian_01"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Strength" },
  },
  ["T_IngFlor_Turnip_01"] = {
    { "DrainAttribute" , "Willpower" },
    "RestoreFatigue",
    "DetectAnimal",
    "Burden",
  },
  ["T_IngMine_Coal_01"] = {
    "DamageHealth",
    "ResistFire",
    "Chameleon",
    { "DrainAttribute" , "Endurance" },
  },
  ["T_IngFood_Tomato_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Endurance" },
    { "DrainAttribute" , "Luck" },
    { "RestoreAttribute" , "Willpower" },
  },
  ["TR_m4_TT_SpawnHackleLo"] = {
    "RestoreFatigue",
    "Paralyze",
    "WaterBreathing",
    { "RestoreAttribute" , "Luck" },
  },
  ["TR_m7_q_Ns_IC8_gem4"] = {
    "DamageHealth",
    "Shield",
    "ResistMagicka",
    "DamageFatigue",
  },
  ["TR_m1_Q_NobleSedge_Stationary"] = {
    "DamageHealth",
    { "RestoreAttribute" , "Agility" },
    "Poison",
    { "FortifyAttribute" , "Agility" },
  },
  ["T_IngFood_Radish_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Speed" },
    "ResistMagicka",
  },
  ["T_IngFlor_FungalPod_01"] = {
    "LightningShield",
    "SwiftSwim",
    { "DrainAttribute" , "Personality" },
    { "DamageAttribute" , "Luck" },
  },
  ["T_IngFlor_Hellebore_01"] = {
    { "DamageAttribute" , "Agility" },
    "ResistShock",
    { "RestoreAttribute" , "Speed" },
    "DamageMagicka",
  },
  ["T_IngMine_SapphireDae_01"] = {
    "DamageHealth",
    "Shield",
    "ResistMagicka",
    "DamageFatigue",
  },
  ["T_IngFlor_IcyShell01"] = {
    "Burden",
    "Poison",
    { "FortifyAttribute" , "Endurance" },
    "FrostShield",
  },
  ["T_IngFood_MeatHorker_01"] = {
    "RestoreFatigue",
    "ResistFrost",
    "WeaknessToFire",
    "RestoreHealth",
  },
  ["T_IngFlor_Nightshade_01"] = {
    "DamageHealth",
    "Burden",
    { "DamageAttribute" , "Luck" },
    "FortifyMagicka",
  },
  ["T_IngFood_MeatChicken_01"] = {
    "RestoreFatigue",
    "Feather",
    { "DrainAttribute" , "Endurance" },
  },
  ["T_IngCrea_BeetleShell_01"] = {
    { "FortifyAttribute" , "Endurance" },
    { "FortifySkill" , "Unarmored" },
  },
  ["T_IngFlor_MonardaSeed_01"] = {
    "ResistCommonDisease",
    "Dispel",
    "DamageMagicka",
    "Silence",
  },
  ["T_IngFlor_ThorntailBerry_01"] = {
    { "DrainAttribute" , "Willpower" },
    { "DrainAttribute" , "Endurance" },
    "RestoreHealth",
    "NightEye",
  },
  ["T_IngFlor_BlueKanet_01"] = {
    { "DrainAttribute" , "Willpower" },
    { "RestoreAttribute" , "Intelligence" },
    "Silence",
    "WeaknessToFire",
  },
  ["TR_m4_TT_SpawnBittergreen"] = {
    { "RestoreAttribute" , "Intelligence" },
    "Invisibility",
    { "DrainAttribute" , "Endurance" },
    "DrainMagicka",
  },
  ["T_IngFlor_Shadowfly_01"] = {
    "Blind",
    "DetectEnchantment",
    "RestoreMagicka",
    "Light",
  },
  ["T_IngFlor_Hibiscus_01"] = {
    "ResistCommonDisease",
    "CurePoison",
    { "DrainAttribute" , "Strength" },
  },
  ["T_IngCrea_AlphynClaw_01"] = {
    { "FortifyAttribute" , "Agility" },
    "Paralyze",
    "Jump",
    { "DrainAttribute" , "Intelligence" },
  },
  ["T_IngMine_Malouchite_01"] = {
    { "DrainAttribute" , "Speed" },
    "Silence",
    "FortifyHealth",
    "Chameleon",
  },
  ["T_IngFlor_PricklyPear_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Willpower" },
    "RestoreHealth",
    "DamageHealth",
  },
  ["TR_m4_menaan_int_8_biscuit"] = {
    "DamageHealth",
    "Poison",
  },
  ["T_IngFood_Wheat_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngFlor_RockburstPod_01"] = {
    "FireDamage",
    "ResistFrost",
    "WeaknessToFire",
    "NightEye",
  },
  ["T_IngDye_YellowOchre_01"] = {
    "Feather",
    { "FortifyAttribute" , "Personality" },
    "RestoreHealth",
  },
  ["T_IngFood_TGuarHide"] = {
    "DrainMagicka",
    { "FortifyAttribute" , "Strength" },
    { "RestoreAttribute" , "Speed" },
    "ResistPoison",
  },
  ["T_IngFlor_WhitePoppyPod_01"] = {
    { "DrainSkill" , "Sneak" },
    "CureCommonDisease",
    "DamageHealth",
    "CurePoison",
  },
  ["T_IngMine_TektiteDae_01"] = {
    "DamageHealth",
    "Paralyze",
    "Reflect",
    { "DrainAttribute" , "Endurance" },
  },
  ["T_IngCrea_PrawnTail"] = {
    "DetectEnchantment",
    { "DrainAttribute" , "Agility" },
    "Telekinesis",
    "Shield",
  },
  ["T_IngCrea_ButterflyWingCyr_01"] = {
    { "RestoreAttribute" , "Agility" },
    "Feather",
    "WeaknessToMagicka",
    "Silence",
  },
  ["T_IngFlor_Motherwort_01"] = {
    "ResistPoison",
    "DamageFatigue",
    "Silence",
    "Invisibility",
  },
  ["T_IngCrea_Ambergris"] = {
    "DrainMagicka",
    { "FortifyAttribute" , "Personality" },
    "Reflect",
    "DetectEnchantment",
  },
  ["TR_m1_q51_ingred_BOmusk_UNI"] = {
    { "DamageAttribute" , "Personality" },
    { "FortifyAttribute" , "Personality" },
    "DamageHealth",
    { "FortifySkill" , "Speechcraft" },
  },
  ["T_IngFood_CheeseBreton_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Agility" },
    "ResistCommonDisease",
  },
  ["T_IngFood_Grape_02"] = {
    "RestoreFatigue",
    { "DamageAttribute" , "Intelligence" },
    "DrainHealth",
    { "RestoreAttribute" , "Personality" },
  },
  ["T_IngFlor_Glasswort_01"] = {
    "DrainHealth",
    { "FortifyAttribute" , "Agility" },
    "Chameleon",
    "FortifyMagicka",
  },
  ["T_IngFlor_AspyrTea_01"] = {
    "RestoreFatigue",
    { "DrainAttribute" , "Agility" },
    "WeaknessToMagicka",
    "CureCommonDisease",
  },
  ["T_IngFlor_LichenOrange_01"] = {
    { "DrainAttribute" , "Endurance" },
    "CureCommonDisease",
    "ResistParalysis",
    "DrainFatigue",
  },
  ["T_IngFood_RiverstriderEgg_01"] = {
    "Paralyze",
    { "DrainAttribute" , "Personality" },
    "Shield",
    "ResistMagicka",
  },
  ["T_IngFood_Blueberry_01"] = {
    "RestoreFatigue",
    "NightEye",
  },
  ["T_IngFood_Plum_01"] = {
    "RestoreFatigue",
    "ResistMagicka",
    "FortifyFatigue",
  },
  ["T_IngCrea_HoomEgg_01"] = {
    "RestoreFatigue",
    "FireDamage",
    { "FortifyAttribute" , "Strength" },
    "ResistNormalWeapons",
  },
  ["T_IngFlor_DriftPuff_01"] = {
    { "DrainAttribute" , "Strength" },
    "SlowFall",
    "Feather",
  },
  ["T_IngFlor_SomberWidow_01"] = {
    "Poison",
    "Blind",
    "ResistMagicka",
  },
  ["T_IngCrea_Termite_01"] = {
    { "FortifyAttribute" , "Strength" },
  },
  ["T_IngFlor_Pitcher_01"] = {
    "DrainMagicka",
    "ResistShock",
    "WaterBreathing",
    { "DrainAttribute" , "Agility" },
  },
  ["T_IngFlor_Cowbell_01"] = {
    "FortifyFatigue",
    "Burden",
    "FrostShield",
    "WeaknessToFire",
  },
  ["T_IngFood_MeatKwama_01"] = {
    "RestoreFatigue",
    "FortifyMagicka",
  },
  ["T_IngFood_MeatAlit_01"] = {
    "ResistPoison",
    "Blind",
    "WeaknessToCommonDisease",
    "RestoreHealth",
  },
  ["TR_m2_q_9_Eyestar_uni"] = {
    "NightEye",
    "Light",
    "WeaknessToMagicka",
    "WaterBreathing",
  },
  ["PC_m1_Anv_DibEstBloodLily"] = {
    { "FortifyAttribute" , "Personality" },
    "DamageHealth",
    "FortifyAttack",
    "FireShield",
  },
  ["T_IngCrea_VelkNectarSack_01"] = {
    "RestoreFatigue",
    "ResistParalysis",
    "CureCommonDisease",
    "WeaknessToFire",
  },
  ["T_IngFlor_Deathbell_01"] = {
    "Poison",
    { "FortifyAttribute" , "Intelligence" },
    "WeaknessToPoison",
    "DetectEnchantment",
  },
  ["T_IngFlor_Persarine_01"] = {
    { "RestoreAttribute" , "Personality" },
    { "FortifyAttribute" , "Luck" },
    "ResistMagicka",
    "RestoreHealth",
  },
  ["T_IngCrea_ButterflyWingCyr_03"] = {
    { "DrainAttribute" , "Agility" },
    "DetectKey",
    "NightEye",
    { "RestoreAttribute" , "Willpower" },
  },
  ["T_IngMine_Citrine_01"] = {
    "WeaknessToShock",
    "CureParalyzation",
    "FortifyFatigue",
    { "FortifyAttribute" , "Intelligence" },
  },
  ["T_IngMine_PearlBlackDae_01"] = {
    "Silence",
    "WaterBreathing",
    { "DamageAttribute" , "Endurance" },
    { "FortifyAttribute" , "Personality" },
  },
  ["T_IngCrea_AstralJellyfish_01"] = {
    "Paralyze",
    "RestoreHealth",
    "DrainFatigue",
    "NightEye",
  },
  ["T_IngCrea_WelkyndDust_01"] = {
    "RestoreMagicka",
    "Light",
    { "DrainAttribute" , "Intelligence" },
    "Levitate",
  },
  ["T_IngMine_Peridot_01"] = {
    "FortifyHealth",
    "RestoreFatigue",
    "DrainMagicka",
    { "FortifyAttribute" , "Intelligence" },
  },
  ["T_IngCrea_BeetleShell_04"] = {
    { "FortifyAttribute" , "Endurance" },
    "FortifyAttack",
  },
  ["T_IngFlor_NgopRoot_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
    "ResistPoison",
  },
  ["T_IngCrea_Mummyheart_01"] = {
    "ResistFrost",
    "DamageMagicka",
    "DrainFatigue",
    "FortifyAttack",
  },
  ["T_IngCrea_TanthaEgg_01"] = {
    "DamageMagicka",
    "ResistParalysis",
    "SlowFall",
  },
  ["T_Glb_UNI_Skyrim_Ice_01"] = {
    "ResistFrost",
    "FrostDamage",
    "FrostShield",
    "Silence",
  },
  ["T_IngFlor_BlackrosePetal_01"] = {
    { "FortifyAttribute" , "Personality" },
    "DrainFatigue",
    "Poison",
    "Invisibility",
  },
  ["T_IngFood_MeatOrnada_01"] = {
    "RestoreFatigue",
    "ResistPoison",
    { "DamageAttribute" , "Strength" },
    { "DrainAttribute" , "Agility" },
  },
  ["T_IngCrea_LamplightResin_01"] = {
    "WeaknessToFire",
    "NightEye",
    { "RestoreAttribute" , "Luck" },
  },
  ["T_IngFood_Blackberry_01"] = {
    "RestoreFatigue",
    "WeaknessToMagicka",
    "ResistCommonDisease",
  },
  ["T_IngFlor_Tobacco_01"] = {
    "RestoreFatigue",
    "ResistParalysis",
    "DamageMagicka",
    "Dispel",
  },
  ["T_IngFlor_SnowBlossom_01"] = {
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Intelligence" },
    "ResistShock",
  },
  ["T_IngSpice_OliveOil_01"] = {
    { "FortifyAttribute" , "Agility" },
    { "DrainAttribute" , "Strength" },
    "Burden",
    "CureParalyzation",
  },
  ["T_IngFlor_Fireflower_01"] = {
    "Light",
    "ResistFrost",
    "Blind",
    "WeaknessToShock",
  },
  ["TR_m2_meteor_i2-383-ind"] = {
    "CurePoison",
    "CureBlightDisease",
    { "RestoreAttribute" , "Willpower" },
    { "FortifyAttribute" , "Willpower" },
  },
  ["T_IngCrea_IcewraithTeeth_01"] = {
    "FrostDamage",
    "FrostShield",
    "Chameleon",
    "FortifyMaximumMagicka",
  },
  ["TR_m7_q_Ns_IC8_gem6"] = {
    "WeaknessToNormalWeapons",
    "DrainFatigue",
    "CurePoison",
    { "FortifyAttribute" , "Personality" },
  },
  ["T_IngFlor_TemarinBugloss_01"] = {
    "ResistPoison",
    "FortifyFatigue",
    "CurePoison",
  },
  ["T_IngFood_EggChicken_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngFlor_HyacinthNectar_01"] = {
    { "DamageAttribute" , "Luck" },
    "DamageFatigue",
    "RestoreMagicka",
    "FortifyMagicka",
  },
  ["T_IngFlor_Jarmush_01"] = {
    "ResistFrost",
    { "DrainAttribute" , "Strength" },
    "RestoreFatigue",
    "Shield",
  },
  ["T_IngMine_Lodestone_01"] = {
    { "DrainAttribute" , "Endurance" },
    "Telekinesis",
    "Burden",
    "ResistShock",
  },
  ["T_IngFlor_GrassPod01"] = {
    "ResistFrost",
    "RestoreFatigue",
    { "DrainAttribute" , "Luck" },
    { "DrainAttribute" , "Intelligence" },
  },
  ["T_IngMine_MoonstoneDae_01"] = {
    "DamageHealth",
    "Reflect",
    "Light",
    { "DrainAttribute" , "Willpower" },
  },
  ["T_IngMine_Salt_01"] = {
    "WeaknessToMagicka",
    "ResistPoison",
  },
  ["T_IngFlor_TrembleWeedSap_01"] = {
    "DamageFatigue",
    { "DrainAttribute" , "Agility" },
    "CureCommonDisease",
    "CureParalyzation",
  },
  ["TR_m3_TT_JalorPowder02"] = {
    "DamageHealth",
    "DamageFatigue",
    { "DamageAttribute" , "Endurance" },
  },
  ["T_IngFlor_WtLillyPink_01"] = {
    "WaterWalking",
    { "DrainAttribute" , "Agility" },
    "Reflect",
    "DrainFatigue",
  },
  ["T_IngFlor_TawnyFunnelCap_01"] = {
    { "RestoreAttribute" , "Intelligence" },
    { "DrainAttribute" , "Endurance" },
    "WeaknessToFire",
    { "RestoreAttribute" , "Luck" },
  },
  ["T_IngDye_Verdigris_01"] = {
    "Light",
    { "FortifyAttribute" , "Personality" },
    "ResistParalysis",
  },
  ["T_IngMine_OreCobalt_01"] = {
    "DrainMagicka",
    "NightEye",
    { "FortifyAttribute" , "Endurance" },
    "ResistFrost",
  },
  ["TR_m7_NVA8_ingred_guar_hide_01"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Endurance" },
    { "RestoreAttribute" , "Personality" },
    { "FortifyAttribute" , "Luck" },
  },
  ["T_IngMine_OreLead_01"] = {
    "Poison",
    "WeaknessToPoison",
    "DamageHealth",
    { "FortifyAttribute" , "Strength" },
  },
  ["T_IngCrea_BosmerBeeswax_01"] = {
    { "RestoreAttribute" , "Strength" },
    { "DrainAttribute" , "Agility" },
    "WeaknessToFrost",
    "CureCommonDisease",
  },
  ["T_IngFlor_ViperBugloss_01"] = {
    "ResistParalysis",
    "NightEye",
    "Burden",
    "CureParalyzation",
  },
  ["T_IngFood_Lyco_01"] = {
    "RestoreFatigue",
    { "RestoreAttribute" , "Luck" },
    "Burden",
  },
  ["T_IngFood_MeatVenison_01"] = {
    "RestoreFatigue",
    "RestoreHealth",
    { "DrainAttribute" , "Strength" },
  },
  ["T_IngCrea_MothWingSky_04"] = {
    "Feather",
    "DrainMagicka",
    "Chameleon",
  },
  ["T_IngFlor_MandrakeRoot_01"] = {
    "CureCommonDisease",
    "ResistPoison",
    { "DamageAttribute" , "Agility" },
    { "FortifyAttribute" , "Willpower" },
  },
  ["T_IngMine_LunarCaustic_01"] = {
    "FireDamage",
    "CureCommonDisease",
    "CurePoison",
    "RestoreHealth",
  },
  ["T_IngMine_KhajiitEye_01"] = {
    "WeaknessToCommonDisease",
    "NightEye",
    { "DrainAttribute" , "Personality" },
    { "FortifyAttribute" , "Speed" },
  },
  ["T_IngFlor_Weepveil_01"] = {
    "DrainMagicka",
    "Dispel",
    "Reflect",
    "Burden",
  },
  ["T_IngFlor_Lavender_01"] = {
    { "RestoreAttribute" , "Agility" },
    "Reflect",
    "RestoreMagicka",
    "FortifyHealth",
  },
}
