return {
  ["hb_ratblood"] = {
    "ResistPoison",
    "WeaknessToBlightDisease",
    "DamageHealth",
    "FrenzyHumanoid",
  },
  ["hb_mudcrabblood"] = {
    { "DamageAttribute" , "Intelligence" },
    "DrainHealth",
    "Chameleon",
    "FrenzyHumanoid",
  },
  ["Hb_netchgland"] = {
    "CureCommonDisease",
    "ResistBlightDisease",
    "SlowFall",
    "Poison",
  },
  ["hb_sprigganbark"] = {
    "CalmCreature",
    "WeaknessToFire",
    "Paralyze",
    "WaterBreathing",
  },
  ["hb_wormmouthblood"] = {
    "Blind",
    "Burden",
    "ResistNormalWeapons",
    "FrenzyHumanoid",
  },
  ["hb_alphynfeather"] = {
    { "FortifyAttribute" , "Speed" },
    "Charm",
    "AbsorbFatigue",
  },
  ["hb_yethbugmeat"] = {
    "SlowFall",
    "Feather",
  },
  ["Hb_alitblood"] = {
    "Poison",
    "DrainHealth",
    "Blind",
    "FrenzyHumanoid",
  },
  ["hb_blackbearskin"] = {
    { "DrainAttribute" , "Speed" },
    { "FortifyAttribute" , "Strength" },
    "NightEye",
    "ResistFrost",
  },
  ["Hb_kagoutiblood"] = {
    "ResistNormalWeapons",
    "AbsorbMagicka",
    { "AbsorbAttribute" , "Intelligence" },
    "FrenzyHumanoid",
  },
  ["hb_spriggansap"] = {
    "CurePoison",
    "RestoreHealth",
    "CureCommonDisease",
    "CureParalyzation",
  },
  ["Hb_plaguebearskin"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Strength" },
    "WeaknessToCommonDisease",
    "NightEye",
  },
  ["hb_animal_eye_fine"] = {
    "Silence",
    "DrainMagicka",
    "NightEye",
  },
  ["hb_horseblood"] = {
    "RestoreFatigue",
    "CalmCreature",
    "Feather",
    "CalmHumanoid",
  },
  ["hb_ingred_kagouti_hide_improved"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Speed" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["hb_horsehide"] = {
    "FortifyFatigue",
    { "FortifySkill" , "Unarmored" },
  },
  ["Hb_racerblood"] = {
    "Levitate",
    "Feather",
    "WeaknessToFire",
    "FrenzyHumanoid",
  },
  ["Hb_snowbearskin"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Strength" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["HB_frosttrollear"] = {
    "Sound",
    "FrostDamage",
    { "FortifyAttribute" , "Strength" },
    { "DrainAttribute" , "Intelligence" },
  },
  ["hb_goatmeat"] = {
    "RestoreFatigue",
    { "FortifyAttribute" , "Speed" },
    "Blind",
    "Burden",
  },
  ["hb_aspisblood"] = {
    "ResistPoison",
    "ResistParalysis",
    "Chameleon",
  },
  ["hb_wormmouthtongue"] = {
    "Sanctuary",
    "Reflect",
    "ResistNormalWeapons",
    "Burden",
  },
  ["Hb_animalfat"] = {
    "WeaknessToFire",
    { "FortifyAttribute" , "Personality" },
    { "DamageAttribute" , "Willpower" },
    "DamageHealth",
  },
  ["hb_grahlpelt"] = {
    "ResistFrost",
    "WeaknessToFire",
    { "FortifyAttribute" , "Strength" },
    "RestoreHealth",
  },
  ["hb_grahlblood"] = {
    "FrostDamage",
    { "FortifyAttribute" , "Strength" },
    "Blind",
    "FrenzyHumanoid",
  },
  ["Hb_normalbearskin"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Strength" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["hb_cervidhide"] = {
    "Sanctuary",
    "Jump",
    "Charm",
  },
  ["hb_aspismeat"] = {
    "NightEye",
    "AbsorbFatigue",
  },
  ["hb_horkerblood"] = {
    "WaterBreathing",
    "SwiftSwim",
    "Telekinesis",
    "FrenzyHumanoid",
  },
  ["hb_cervidblood"] = {
    "RestoreHealth",
    { "AbsorbAttribute" , "Strength" },
    "NightEye",
    "CalmHumanoid",
  },
  ["hb_mooncrabblod"] = {
    { "DamageAttribute" , "Personality" },
    "WeaknessToMagicka",
  },
  ["hb_animalheart"] = {
    "RestoreHealth",
    { "FortifyAttribute" , "Strength" },
    "Poison",
    "NightEye",
  },
  ["hb_boarblood"] = {
    "FrenzyCreature",
    "ResistFrost",
    { "FortifyAttribute" , "Strength" },
    "FrenzyHumanoid",
  },
  ["hb_animalteeth_misc"] = {
    "DrainHealth",
    "Dispel",
    "Reflect",
    "Paralyze",
  },
  ["hb_crab_eggs_roe"] = {
    "RestoreFatigue",
    { "AbsorbAttribute" , "Intelligence" },
    "SwiftSwim",
  },
  ["hb_muskratblood"] = {
    "ResistPoison",
    { "AbsorbAttribute" , "Luck" },
    { "DamageSkill" , "Speechcraft" },
    "Burden",
  },
  ["hb_venom"] = {
    "Poison",
    "Paralyze",
  },
  ["hb_frogmeat"] = {
    { "FortifyAttribute" , "Agility" },
    { "FortifyAttribute" , "Strength" },
    "Blind",
    "DamageMagicka",
  },
  ["hb_wolfmeat"] = {
    "Jump",
    "FortifyHealth",
    "CurePoison",
    "ResistPoison",
  },
  ["hb_frogblood"] = {
    "WaterBreathing",
    "SwiftSwim",
    { "DamageAttribute" , "Intelligence" },
  },
  ["hb_goatpelt"] = {
    "ResistFrost",
    "RestoreHealth",
  },
  ["Hb_plaguewolfskin"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Speed" },
    "WeaknessToCommonDisease",
    "NightEye",
  },
  ["hb_ingred_alit_hide_improved"] = {
    { "DrainAttribute" , "Intelligence" },
    "ResistPoison",
    "Telekinesis",
    "DetectAnimal",
  },
  ["hb_tanthablood"] = {
    "Invisibility",
    "Sanctuary",
  },
  ["hb_insectmeat"] = {
    "Poison",
    "Paralyze",
    "AbsorbMagicka",
  },
  ["Hb_kagouti_horn"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Endurance" },
    { "RestoreAttribute" , "Personality" },
    { "FortifyAttribute" , "Luck" },
  },
  ["hb_ingred_guar_hide_improved"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Endurance" },
    { "RestoreAttribute" , "Personality" },
    { "FortifyAttribute" , "Luck" },
  },
  ["Hb_normalwolfskin"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Speed" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["hb_goatpeltmountain"] = {
    "ResistFrost",
    "RestoreHealth",
  },
  ["hb_alphynmeat"] = {
    "RestoreHealth",
    "FortifyHealth",
  },
  ["Hb_netchleatherimproved"] = {
    { "FortifyAttribute" , "Endurance" },
    { "FortifyAttribute" , "Intelligence" },
    { "DrainAttribute" , "Personality" },
    "CureParalyzation",
  },
  ["hb_trollpelt"] = {
    { "DamageAttribute" , "Intelligence" },
    "ResistCommonDisease",
    { "FortifyAttribute" , "Strength" },
    "RestoreHealth",
  },
  ["hb_trollblood"] = {
    "RestoreHealth",
    "NightEye",
    "FrenzyCreature",
    "FrenzyHumanoid",
  },
  ["Hb_boarfurpelt"] = {
    "ResistFrost",
    "ResistNormalWeapons",
    "AbsorbFatigue",
    "WeaknessToFire",
  },
  ["Hb_bearblood"] = {
    "ResistNormalWeapons",
    { "FortifyAttribute" , "Agility" },
    "Blind",
    "FrenzyHumanoid",
  },
  ["Hb_wolfblood"] = {
    "NightEye",
    "Feather",
    "DrainFatigue",
    "FrenzyHumanoid",
  },
  ["Hb_snowwolfskin"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Speed" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["Hb_guartongue"] = {
    { "DrainAttribute" , "Personality" },
    "RestoreHealth",
    { "FortifyAttribute" , "Strength" },
    "ResistPoison",
  },
  ["HB_netchbettyjelly"] = {
    "Paralyze",
    { "FortifyAttribute" , "Strength" },
    "RestoreFatigue",
    "Levitate",
  },
  ["hb_animal_eye_clumsy"] = {
    "DrainMagicka",
  },
  ["Hb_ratfurpelt"] = {
    "DrainHealth",
    "DrainFatigue",
    "Blind",
    "Feather",
  },
  ["hb_goatblood"] = {
    { "DamageAttribute" , "Intelligence" },
    "Jump",
    "CalmCreature",
    "FrenzyHumanoid",
  },
  ["Hb_netchbulljelly"] = {
    "Paralyze",
    { "FortifyAttribute" , "Strength" },
    "RestoreFatigue",
    "Levitate",
  },
  ["hb_goathorn"] = {
    { "AbsorbAttribute" , "Intelligence" },
    "FortifyFatigue",
    "ShockDamage",
    "Sound",
  },
  ["Hb_nixhoundblood"] = {
    "Silence",
    "Sound",
    "Jump",
    "FrenzyHumanoid",
  },
  ["Hb_tanthameat"] = {
    { "FortifySkill" , "Sneak" },
    { "FortifyAttribute" , "Agility" },
  },
  ["Hb_scribblood"] = {
    "Poison",
    "Paralyze",
    "Dispel",
    "FrenzyHumanoid",
  },
  ["hb_alphynblood"] = {
    "NightEye",
    "Levitate",
    "Sound",
  },
  ["hb_dreughblood"] = {
    "WaterBreathing",
    "SwiftSwim",
    "RestoreHealth",
    "FrenzyHumanoid",
  },
  ["hb_fishbaitmeat"] = {
    "CalmCreature",
  },
  ["hb_stridentmeat"] = {
    "SlowFall",
    "Feather",
  },
  ["hb_bearmeat"] = {
    "RestoreHealth",
    { "DrainAttribute" , "Speed" },
    { "DamageAttribute" , "Agility" },
    "RestoreFatigue",
  },
  ["hb_STRIDENTblood"] = {
    "Jump",
    { "DrainAttribute" , "Intelligence" },
    "Blind",
  },
  ["Hb_fish_eggs_roe"] = {
    "RestoreFatigue",
    "FortifyFatigue",
    "WaterBreathing",
  },
  ["hb_animal_eye_mediocre"] = {
    "Silence",
    "DrainMagicka",
  },
  ["Hb_guarblood"] = {
    "NightEye",
    "DetectAnimal",
    "Burden",
    "FrenzyHumanoid",
  },
  ["Hb_animalblood"] = {
    "Dispel",
    { "FortifyAttribute" , "Strength" },
    "RestoreFatigue",
    "FrenzyHumanoid",
  },
  ["Hb_horkerfurpelt"] = {
    "WaterBreathing",
    "RestoreMagicka",
    { "DrainAttribute" , "Speed" },
    "SwiftSwim",
  },
  ["hb_hemolymph_vial"] = {
    "Poison",
    "Paralyze",
    "Dispel",
    "WeaknessToFire",
  },
  ["hb_hemolymph"] = {
    "Poison",
    "Paralyze",
    "Dispel",
    "WeaknessToFire",
  },
  ["hb_animal_eye_perfect"] = {
    { "FortifyAttribute" , "Intelligence" },
    "DrainMagicka",
    "NightEye",
    "Silence",
  },
  ["hb_snakemeat"] = {
    "Jump",
    "FortifyHealth",
    "CurePoison",
    "ResistPoison",
  },
  ["hb_baitrandom"] = {
    "WaterBreathing",
    "WaterBreathing",
    "WaterBreathing",
    "WaterBreathing",
  },
}
