return {
  ["ingred_bittergreen_petals_01"] = {
    { "RestoreAttribute" , "Intelligence" },
    "Invisibility",
    { "DrainAttribute" , "Endurance" },
    "DrainMagicka",
  },
  ["ingred_void_salts_01"] = {
    "RestoreMagicka",
    "SpellAbsorption",
    "Paralyze",
    { "DrainAttribute" , "Endurance" },
  },
  ["ingred_raw_glass_tinos"] = {
    { "DrainAttribute" , "Intelligence" },
    { "DrainAttribute" , "Strength" },
    { "DrainAttribute" , "Speed" },
    "FireShield",
  },
  ["ingred_rat_meat_01"] = {
    "DrainMagicka",
    "Paralyze",
    "CurePoison",
    "ResistPoison",
  },
  ["ingred_russula_01"] = {
    "WaterBreathing",
    "DrainFatigue",
    "Poison",
  },
  ["ingred_guar_hide_girith"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Endurance" },
    { "RestoreAttribute" , "Personality" },
    { "FortifyAttribute" , "Luck" },
  },
  ["ingred_kwama_cuttle_01"] = {
    "ResistPoison",
    "DrainFatigue",
    "WaterWalking",
    "WaterBreathing",
  },
  ["ingred_scrib_jelly_02"] = {
    { "FortifyAttribute" , "Willpower" },
    "CurePoison",
    "CureBlightDisease",
    { "RestoreAttribute" , "Willpower" },
  },
  ["ingred_adamantium_ore_01"] = {
    "Burden",
    "RestoreMagicka",
    "Poison",
    "Reflect",
  },
  ["ingred_scales_01"] = {
    { "DrainAttribute" , "Personality" },
    "WaterWalking",
    { "RestoreAttribute" , "Endurance" },
    "SwiftSwim",
  },
  ["ingred_6th_corprusmeat_04"] = {
    "DrainFatigue",
    "DrainHealth",
    "DrainMagicka",
  },
  ["ingred_corkbulb_root_01"] = {
    "CureParalyzation",
    "RestoreHealth",
    "LightningShield",
    { "FortifyAttribute" , "Luck" },
  },
  ["ingred_ash_yam_01"] = {
    { "FortifyAttribute" , "Intelligence" },
    { "FortifyAttribute" , "Strength" },
    "ResistCommonDisease",
    "DetectKey",
  },
  ["ingred_daedra_skin_01"] = {
    { "FortifyAttribute" , "Strength" },
    "CureCommonDisease",
    "Paralyze",
    "SwiftSwim",
  },
  ["Ingred_sweetpulp_01"] = {
    "Paralyze",
    "Levitate",
    "ResistParalysis",
    "RestoreHealth",
  },
  ["ingred_kresh_fiber_01"] = {
    { "RestoreAttribute" , "Luck" },
    { "FortifyAttribute" , "Personality" },
    "DrainMagicka",
    { "DrainAttribute" , "Speed" },
  },
  ["Ingred_golden_sedge_01"] = {
    "DrainMagicka",
    { "FortifyAttribute" , "Strength" },
    "FortifyAttack",
    "SwiftSwim",
  },
  ["ingred_netch_leather_01"] = {
    { "FortifyAttribute" , "Endurance" },
    { "FortifyAttribute" , "Intelligence" },
    { "DrainAttribute" , "Personality" },
    "CureParalyzation",
  },
  ["ingred_Dae_cursed_emerald_01"] = {
    "FortifyMagicka",
    "RestoreHealth",
    { "DrainAttribute" , "Agility" },
    { "DrainAttribute" , "Endurance" },
  },
  ["ingred_crab_meat_01"] = {
    "RestoreFatigue",
    "ResistShock",
    "LightningShield",
    { "RestoreAttribute" , "Luck" },
  },
  ["ingred_Dae_cursed_pearl_01"] = {
    { "DrainAttribute" , "Agility" },
    "Dispel",
    "WaterBreathing",
    "ResistCommonDisease",
  },
  ["ingred_black_lichen_01"] = {
    { "DrainAttribute" , "Strength" },
    "ResistFrost",
    { "DrainAttribute" , "Speed" },
    "CurePoison",
  },
  ["ingred_6th_corprusmeat_07"] = {
    "DrainFatigue",
    "DrainHealth",
    "DrainMagicka",
  },
  ["ingred_comberry_01"] = {
    "DrainFatigue",
    "RestoreMagicka",
    "FireShield",
    "Reflect",
  },
  ["ingred_racer_plumes_01"] = {
    { "DrainAttribute" , "Willpower" },
    "Levitate",
  },
  ["ingred_horker_tusk_01"] = {
    { "DrainSkill" , "Alteration" },
    { "FortifyAttribute" , "Intelligence" },
    "FortifyMaximumMagicka",
    "DetectAnimal",
  },
  ["ingred_stoneflower_petals_01"] = {
    { "RestoreAttribute" , "Strength" },
    "FortifyMagicka",
    { "DrainAttribute" , "Luck" },
    { "FortifyAttribute" , "Personality" },
  },
  ["ingred_emerald_01"] = {
    "FortifyMagicka",
    "RestoreHealth",
    { "DrainAttribute" , "Agility" },
    { "DrainAttribute" , "Endurance" },
  },
  ["ingred_durzog_meat_01"] = {
    { "FortifyAttribute" , "Agility" },
    { "FortifyAttribute" , "Strength" },
    "Blind",
    "DamageMagicka",
  },
  ["ingred_chokeweed_01"] = {
    { "DrainAttribute" , "Luck" },
    "RestoreFatigue",
    "CureCommonDisease",
    { "DrainAttribute" , "Willpower" },
  },
  ["ingred_holly_01"] = {
    "ResistFrost",
    "FrostShield",
    "FrostDamage",
    "WeaknessToFire",
  },
  ["Ingred_horn_lily_bulb_01"] = {
    "ResistParalysis",
    "DrainHealth",
    { "RestoreAttribute" , "Strength" },
    { "RestoreAttribute" , "Endurance" },
  },
  ["ingred_6th_corprusmeat_05"] = {
    "DrainFatigue",
    "DrainHealth",
    "DrainMagicka",
  },
  ["ingred_innocent_heart"] = {
    "RestoreMagicka",
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Agility" },
    "NightEye",
  },
  ["ingred_bc_ampoule_pod"] = {
    "WaterWalking",
    "Paralyze",
    "DetectAnimal",
    { "DrainAttribute" , "Willpower" },
  },
  ["ingred_belladonna_02"] = {
    "ResistMagicka",
    "RestoreMagicka",
    "FortifyMagicka",
    "DrainMagicka",
  },
  ["ingred_gravetar_01"] = {
    "ResistFrost",
    "DrainHealth",
    "FortifyFatigue",
    { "DrainAttribute" , "Luck" },
  },
  ["ingred_bonemeal_01"] = {
    { "RestoreAttribute" , "Agility" },
    "Telekinesis",
    "DrainFatigue",
    { "DrainAttribute" , "Personality" },
  },
  ["ingred_scrib_jelly_01"] = {
    { "FortifyAttribute" , "Willpower" },
    "CurePoison",
    "CureBlightDisease",
    { "RestoreAttribute" , "Willpower" },
  },
  ["ingred_sload_soap_01"] = {
    { "DrainAttribute" , "Personality" },
    { "FortifyAttribute" , "Agility" },
    "FireShield",
    { "RestoreAttribute" , "Agility" },
  },
  ["ingred_raw_Stalhrim_01"] = {
    "ResistFrost",
    "FrostDamage",
    "Paralyze",
    "RestoreHealth",
  },
  ["Ingred_meadow_rye_01"] = {
    { "FortifyAttribute" , "Speed" },
    "DamageHealth",
    { "RestoreAttribute" , "Speed" },
    { "DrainAttribute" , "Speed" },
  },
  ["ingred_marshmerrow_01"] = {
    "RestoreHealth",
    "DetectEnchantment",
    { "DrainAttribute" , "Willpower" },
    "DrainFatigue",
  },
  ["ingred_wolfsbane_01"] = {
    { "RestoreAttribute" , "Intelligence" },
    "Invisibility",
    { "DrainAttribute" , "Endurance" },
    "DrainMagicka",
  },
  ["ingred_treated_bittergreen_uniq"] = {
    { "RestoreAttribute" , "Intelligence" },
    "DrainMagicka",
    { "DrainAttribute" , "Endurance" },
    "Invisibility",
  },
  ["ingred_hackle-lo_leaf_01"] = {
    "RestoreFatigue",
    "Paralyze",
    "WaterBreathing",
    { "RestoreAttribute" , "Luck" },
  },
  ["ingred_green_lichen_01"] = {
    { "FortifyAttribute" , "Personality" },
    "CureCommonDisease",
    { "DrainAttribute" , "Strength" },
    "DrainHealth",
  },
  ["Ingred_timsa-come-by_01"] = {
    "Dispel",
    "ResistParalysis",
    "DrainMagicka",
    { "RestoreAttribute" , "Endurance" },
  },
  ["ingred_gold_kanet_01"] = {
    "DrainHealth",
    "Burden",
    { "DrainAttribute" , "Luck" },
    { "RestoreAttribute" , "Strength" },
  },
  ["ingred_moon_sugar_01"] = {
    { "FortifyAttribute" , "Speed" },
    "Dispel",
    { "DrainAttribute" , "Endurance" },
    { "DrainAttribute" , "Luck" },
  },
  ["ingred_eyeball"] = {
    "ResistFrost",
    "NightEye",
    "DrainMagicka",
    { "FortifyAttribute" , "Strength" },
  },
  ["ingred_red_lichen_01"] = {
    { "DrainAttribute" , "Speed" },
    "Light",
    "CureCommonDisease",
    "DrainMagicka",
  },
  ["ingred_frost_salts_01"] = {
    { "DrainAttribute" , "Speed" },
    "RestoreMagicka",
    "FrostShield",
    "ResistFire",
  },
  ["ingred_heather_01"] = {
    { "RestoreAttribute" , "Personality" },
    "Feather",
    { "DrainAttribute" , "Speed" },
    { "DrainAttribute" , "Personality" },
  },
  ["ingred_alit_hide_01"] = {
    { "DrainAttribute" , "Intelligence" },
    "ResistPoison",
    "Telekinesis",
    "DetectAnimal",
  },
  ["ingred_willow_anther_01"] = {
    { "DrainAttribute" , "Personality" },
    "FrostShield",
    "CureCommonDisease",
    "CureParalyzation",
  },
  ["ingred_trama_root_01"] = {
    { "RestoreAttribute" , "Willpower" },
    "Levitate",
    "DrainMagicka",
    { "DrainAttribute" , "Speed" },
  },
  ["ingred_heartwood_01"] = {
    "RestoreMagicka",
    { "FortifyAttribute" , "Agility" },
    { "DrainAttribute" , "Strength" },
    "WeaknessToFire",
  },
  ["ingred_Dae_cursed_diamond_01"] = {
    { "DrainAttribute" , "Agility" },
    "Invisibility",
    "Reflect",
    "DetectKey",
  },
  ["ingred_eyeball_unique"] = {
    "ResistFrost",
    "NightEye",
    "DrainMagicka",
    { "FortifyAttribute" , "Strength" },
  },
  ["ingred_gold_kanet_unique"] = {
    "DrainHealth",
    "Burden",
    { "DrainAttribute" , "Luck" },
    { "RestoreAttribute" , "Strength" },
  },
  ["Ingred_noble_sedge_01"] = {
    "DamageHealth",
    { "RestoreAttribute" , "Agility" },
    "Poison",
    { "FortifyAttribute" , "Agility" },
  },
  ["poison_goop00"] = {
    "WeaknessToPoison",
    "DamageHealth",
    "DamageFatigue",
    "Poison",
  },
  ["ingred_resin_01"] = {
    "RestoreHealth",
    { "RestoreAttribute" , "Speed" },
    "Burden",
    "ResistCommonDisease",
  },
  ["ingred_ruby_01"] = {
    "DrainHealth",
    "Feather",
    { "RestoreAttribute" , "Intelligence" },
    { "DrainAttribute" , "Agility" },
  },
  ["ingred_guar_hide_01"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Endurance" },
    { "RestoreAttribute" , "Personality" },
    { "FortifyAttribute" , "Luck" },
  },
  ["Ingred_nirthfly_stalks_01"] = {
    "DamageHealth",
    { "FortifyAttribute" , "Speed" },
    { "RestoreAttribute" , "Speed" },
    { "DrainAttribute" , "Speed" },
  },
  ["ingred_ectoplasm_01"] = {
    { "FortifyAttribute" , "Agility" },
    "DetectAnimal",
    { "DrainAttribute" , "Strength" },
    "DrainHealth",
  },
  ["ingred_udyrfrykte_heart"] = {
    "RestoreMagicka",
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Agility" },
    "NightEye",
  },
  ["ingred_cursed_daedras_heart_01"] = {
    "RestoreMagicka",
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Agility" },
    "NightEye",
  },
  ["ingred_human_meat_01"] = {
    "FortifyHealth",
    { "DrainAttribute" , "Intelligence" },
    { "DrainAttribute" , "Personality" },
  },
  ["ingred_wickwheat_01"] = {
    "RestoreHealth",
    { "FortifyAttribute" , "Willpower" },
    "Paralyze",
    { "DamageAttribute" , "Intelligence" },
  },
  ["food_kwama_egg_02"] = {
    "RestoreFatigue",
    "Paralyze",
    "FrostShield",
    "FortifyHealth",
  },
  ["ingred_fire_salts_01"] = {
    "DrainHealth",
    { "FortifyAttribute" , "Agility" },
    "ResistFrost",
    "FireShield",
  },
  ["ingred_kagouti_hide_01"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Speed" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["ingred_scrib_jerky_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
    "Burden",
    "SwiftSwim",
  },
  ["ingred_Dae_cursed_ruby_01"] = {
    "DrainHealth",
    "Feather",
    { "RestoreAttribute" , "Intelligence" },
    { "DrainAttribute" , "Agility" },
  },
  ["ingred_snowwolf_pelt_unique"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Speed" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["ingred_bc_coda_flower"] = {
    { "DrainAttribute" , "Personality" },
    "Levitate",
    { "DrainAttribute" , "Intelligence" },
    "DrainHealth",
  },
  ["ingred_scuttle_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
    "Feather",
    "Telekinesis",
  },
  ["ingred_dreugh_wax_01"] = {
    { "FortifyAttribute" , "Strength" },
    { "RestoreAttribute" , "Strength" },
    { "DrainAttribute" , "Luck" },
    { "DrainAttribute" , "Willpower" },
  },
  ["ingred_bc_hypha_facia"] = {
    { "DrainAttribute" , "Luck" },
    { "DrainAttribute" , "Agility" },
    "DrainFatigue",
    "DetectEnchantment",
  },
  ["ingred_belladonna_01"] = {
    "ResistMagicka",
    "RestoreMagicka",
    "FortifyMagicka",
    "DrainMagicka",
  },
  ["ingred_scathecraw_01"] = {
    { "DrainAttribute" , "Strength" },
    "CurePoison",
    "DrainHealth",
    { "RestoreAttribute" , "Willpower" },
  },
  ["ingred_scrap_metal_01"] = {
    "DrainHealth",
    "LightningShield",
    "ResistShock",
    { "RestoreAttribute" , "Intelligence" },
  },
  ["ingred_shalk_resin_01"] = {
    "DrainFatigue",
    "FortifyHealth",
    { "DrainAttribute" , "Personality" },
    { "FortifyAttribute" , "Speed" },
  },
  ["ingred_saltrice_01"] = {
    "RestoreFatigue",
    "FortifyMagicka",
    { "DrainAttribute" , "Strength" },
    "RestoreHealth",
  },
  ["ingred_black_anther_01"] = {
    { "DrainAttribute" , "Agility" },
    "ResistFire",
    { "DrainAttribute" , "Endurance" },
    "Light",
  },
  ["ingred_diamond_01"] = {
    { "DrainAttribute" , "Agility" },
    "Invisibility",
    "Reflect",
    "DetectKey",
  },
  ["ingred_bloat_01"] = {
    "DrainMagicka",
    { "FortifyAttribute" , "Intelligence" },
    { "FortifyAttribute" , "Willpower" },
    "DetectAnimal",
  },
  ["ingred_6th_corprusmeat_01"] = {
    "DrainFatigue",
    "DrainHealth",
    "DrainMagicka",
  },
  ["ingred_snowbear_pelt_unique"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Speed" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["ingred_6th_corprusmeat_06"] = {
    "DrainFatigue",
    "DrainHealth",
    "DrainMagicka",
  },
  ["ingred_wolf_pelt"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Speed" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["Ingred_scrib_cabbage_01"] = {
    { "DrainAttribute" , "Intelligence" },
    "DamageHealth",
    { "RestoreAttribute" , "Agility" },
    { "FortifyAttribute" , "Agility" },
  },
  ["ingred_corprus_weepings_01"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Luck" },
    { "DrainAttribute" , "Willpower" },
    "RestoreHealth",
  },
  ["ingred_bc_spore_pod"] = {
    { "DrainAttribute" , "Strength" },
    "DrainFatigue",
    "DetectKey",
    "Paralyze",
  },
  ["ingred_boar_leather"] = {
    "Blind",
    "FrostDamage",
    "ResistFrost",
    "Recall",
  },
  ["ingred_Dae_cursed_raw_ebony_01"] = {
    { "DrainAttribute" , "Agility" },
    "CurePoison",
    "FrostShield",
    { "RestoreAttribute" , "Speed" },
  },
  ["ingred_6th_corprusmeat_03"] = {
    "DrainFatigue",
    "DrainHealth",
    "DrainMagicka",
  },
  ["ingred_guar_hide_marsus"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Endurance" },
    { "RestoreAttribute" , "Personality" },
    { "FortifyAttribute" , "Luck" },
  },
  ["ingred_wolf_heart"] = {
    "RestoreMagicka",
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Agility" },
    "NightEye",
  },
  ["ingred_fire_petal_01"] = {
    "ResistFire",
    "DrainHealth",
    "SpellAbsorption",
    "Paralyze",
  },
  ["ingred_blood_innocent_unique"] = {
    { "DrainAttribute" , "Speed" },
    "Light",
    "CureCommonDisease",
    "DrainMagicka",
  },
  ["ingred_hound_meat_01"] = {
    "RestoreFatigue",
    "FortifyFatigue",
    "Reflect",
    "DetectEnchantment",
  },
  ["ingred_scamp_skin_01"] = {
    "DrainMagicka",
    "CureParalyzation",
    { "RestoreAttribute" , "Personality" },
    { "RestoreAttribute" , "Strength" },
  },
  ["ingred_ash_salts_01"] = {
    { "DrainAttribute" , "Agility" },
    "ResistMagicka",
    "CureBlightDisease",
    "ResistMagicka",
  },
  ["ingred_daedras_heart_01"] = {
    "RestoreMagicka",
    { "FortifyAttribute" , "Endurance" },
    { "DrainAttribute" , "Agility" },
    "NightEye",
  },
  ["ingred_muck_01"] = {
    { "DrainAttribute" , "Intelligence" },
    "DetectKey",
    { "DrainAttribute" , "Personality" },
    "CureCommonDisease",
  },
  ["Ingred_lloramor_spines_01"] = {
    "SpellAbsorption",
    "Invisibility",
    "Poison",
    "DetectEnchantment",
  },
  ["ingred_vampire_dust_01"] = {
    "FortifyHealth",
    { "FortifyAttribute" , "Strength" },
    "SpellAbsorption",
    "Vampirism",
  },
  ["ingred_coprinus_01"] = {
    "WaterWalking",
    "DrainFatigue",
    "Poison",
  },
  ["ingred_pearl_01"] = {
    { "DrainAttribute" , "Agility" },
    "Dispel",
    "WaterBreathing",
    "ResistCommonDisease",
  },
  ["ingred_gravedust_01"] = {
    { "DrainAttribute" , "Intelligence" },
    "CureCommonDisease",
    "DrainMagicka",
    { "RestoreAttribute" , "Endurance" },
  },
  ["ingred_6th_corprusmeat_02"] = {
    "DrainFatigue",
    "DrainHealth",
    "DrainMagicka",
  },
  ["ingred_bear_pelt"] = {
    "DrainFatigue",
    { "FortifyAttribute" , "Strength" },
    "ResistCommonDisease",
    "NightEye",
  },
  ["ingred_raw_glass_01"] = {
    { "DrainAttribute" , "Intelligence" },
    { "DrainAttribute" , "Strength" },
    { "DrainAttribute" , "Speed" },
    "FireShield",
  },
  ["ingred_raw_ebony_01"] = {
    { "DrainAttribute" , "Agility" },
    "CurePoison",
    "FrostShield",
    { "RestoreAttribute" , "Speed" },
  },
  ["ingred_emerald_pinetear"] = {
    "FortifyMagicka",
    "RestoreHealth",
    { "DrainAttribute" , "Agility" },
    { "DrainAttribute" , "Endurance" },
  },
  ["ingred_roobrush_01"] = {
    { "DrainAttribute" , "Willpower" },
    { "FortifyAttribute" , "Agility" },
    "DrainHealth",
    "CurePoison",
  },
  ["ingred_bc_bungler's_bane"] = {
    { "DrainAttribute" , "Speed" },
    { "DrainAttribute" , "Endurance" },
    "Dispel",
    { "DrainAttribute" , "Strength" },
  },
  ["ingred_ghoul_heart_01"] = {
    "Paralyze",
    "CurePoison",
    "FortifyAttack",
  },
}
